"""Localized, offline user documentation displayed by the desktop client."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HelpTopic:
    key: str
    title: str
    body: str


_EN = (
    ("overview", "1. TuxDrive overview", "TuxDrive synchronizes selected folders with eight cloud providers, mounts files on demand, and connects encrypted peer folders without storing peer data on a TuxDrive server. The left side lists accounts; the center lists jobs; the bottom log explains current activity. Provider icons identify the storage service and state text/badges show connected, syncing, paused, or error conditions.\n\nHOW TO START\n1. Connect an account. 2. Add a synchronized folder or streaming drive. 3. Review the cloud path, local path, direction and safety settings. 4. Keep an independent backup before the first two-way synchronization."),
    ("accounts", "2. Cloud accounts and authentication", "Use + or Connect account for Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive, or Nextcloud. Browser-OAuth providers open their own login page; TuxDrive never receives that password. Proton/MEGA/Nextcloud use guided credentials and Proton can request a separate 2FA code. Credentials are stored through encrypted rclone configuration protected by Secret Service.\n\nHOW TO REPAIR AUTHORIZATION\nOpen the account menu → Reconnect / refresh credentials. Complete authorization and wait for cloud verification. Remove an account only after deleting jobs that use it."),
    ("selective", "3. Folder selection and cloud locations", "The visual tree loads folders lazily. Check one or more folders, expand arrows to browse deeper, or select the entire drive. Google Drive exposes My Drive, Shared with me, and each Shared Drive as separate locations. One selected cloud folder creates one job and local destination.\n\nHOW TO CHANGE SELECTION\nChoose Edit on a job, select the intended drive/location and tree nodes, verify that local destinations do not overlap unsafely, then save."),
    ("sync", "4. Synchronization modes and callbacks", "Two-way sync propagates creations, modifications, moves and deletions in both directions. Download-only/receive-only protects the cloud side; upload-only/send-only protects the local side. Real-time callbacks detect saved local changes and transfer changed paths; polling detects remote changes. Block-delta transfer is used for supported direct peers.\n\nHOW TO RUN OR PAUSE\nSync now starts a run. Stop cancels the active process. The compact switch enables or pauses automatic work. Check the status and View log before forcing recovery after an error."),
    ("streaming", "5. Files on demand and offline availability", "A streaming drive mounts the cloud hierarchy with FUSE. Folder names appear immediately while file bodies download when opened. The mount point must be empty. A streaming child can live inside a normal synchronized tree because TuxDrive excludes that subtree; a streaming parent of another sync is unsafe.\n\nHOW TO USE\nAdd folder → Streaming drive, choose the cloud subtree and empty mount folder, then Start streaming. In Nautilus right-click a streamed item to keep it offline or return it to online-only. Disconnect cleanly before deleting a mount point."),
    ("actions", "6. Job buttons and online folders", "Open folder opens the local destination. Open online opens the exact provider folder when supported. Share link requests a provider link and copies it. Rename changes only the label inside TuxDrive. Edit changes paths, mode, interval, filters and protection. View log opens transfer logs. The trash button removes the job definition but does not delete local or cloud data."),
    ("safety", "7. Recovery, versions, integrity and ransomware protection", "History restores locally retained versions and recycled deletions. Verify compares local/cloud content and offers selected repairs. Conflicts opens mismatches for explicit review. Mass-change/ransomware protection pauses suspicious deletion or extension bursts before propagation; it is a safety boundary, not antivirus. Maximum deletions limits destructive runs.\n\nHOW TO RECOVER\nStop the job, inspect View log and Conflicts, restore a known-good version, verify both sides, then resume. Never approve a mass-change event until the source device is clean."),
    ("exceptions", "8. Exceptions, conflicts and unsafe provider files", "Synchronization exceptions are clickable rules. Add temporary/lock files or a failing path after reviewing the error; remove a rule to include it again. Google files flagged as malware/spam require an explicit unsafe-download acknowledgement. Conflict policy can keep both copies, prefer local, or prefer cloud; keeping both is safest when uncertain."),
    ("peer", "9. Private peer-to-peer folders", "Peer sharing uses authenticated, host-key-pinned SFTP and individual device identity keys. A host selects a folder, address/port and authorized devices; guests import a signed invitation/QR and select a local folder. Roles are read/write, read-only, send-only or receive-only. LAN discovery finds candidates but users must verify fingerprints. Optional NAT mapping or ciphertext-only relay can help reachability.\n\nHOW TO PAIR\nExchange public keys through a trusted channel, authorize the named device, copy the invitation, verify the host fingerprint on the guest, then connect. Revoke a lost device and restart the share."),
    ("privacy", "10. Tor and fail-closed privacy", "A peer workspace can publish a Tor v3 Onion Service, optionally persistent and protected with per-device client authorization. Policies include Tor only, direct only, no relay, no public-IP discovery, and never use provider cloud. Violations pause traffic instead of falling back silently. Bridges/pluggable transports are advanced settings and secrets are excluded from invitations/logs.\n\nHOW TO USE TOR ONLY\nInstall Tor, choose Tor only, enable Onion Service and optionally client authorization, save/start, then distribute the private invitation securely. Confirm that no direct/relay endpoint appears."),
    ("collaboration", "11. Collaborative documents", "Markdown/text uses an operation CRDT: peers edit offline, immutable operations synchronize, and deterministic merge produces the same text. Collaboration state stays in .tuxdrive-collaboration; Export checkpoint writes an ordinary file. Optional encrypted presence shows cursors/selections briefly without permanent audit storage. Comments, suggestions, tracked changes, approvals and tasks are review events.\n\nODT/ODS support is experimental structured import/export with deterministic snapshots and original XML recovery. DOCX/XLSX/PDF remain under leases, versions and review, not real-time editing."),
    ("profile", "12. Encrypted profile backup and migration", "Settings → TuxDrive Profile / migrate encrypts configuration locally with AES-256-GCM/scrypt and stores it in a selected OAuth provider. By default OAuth credentials and peer private keys are excluded. Sensitive inclusion is explicit and requires the same strong password during restore. TuxDrive cannot recover that password.\n\nHOW TO MIGRATE\nBack up on the old device, install TuxDrive on the new device, connect the same provider, inspect the discovered backup, restore, then reauthorize excluded accounts and verify every path before enabling jobs."),
    ("nautilus", "13. Nautilus integration", "When enabled, Nautilus displays synchronized/syncing/pending/paused/error/streaming emblems and context actions for sync, online folder, logs and offline availability. The extension reads a private state file and sends actions to the running application. Disable it in Settings if another extension conflicts, then restart Nautilus."),
    ("updates", "14. Secure in-app updates", "Settings → Check for updates downloads a signed expiring manifest. TuxDrive verifies Ed25519 signature, approved repository URL, SHA-256, package identity/version and size before PolicyKit asks for administrator authorization. A failed verification leaves the current installation unchanged.\n\nHOW TO UPDATE\nCheck, review version/notes, Download and install, approve the system prompt, then restart TuxDrive. If it claims an old version is current, wait briefly for repository cache refresh and retry."),
    ("policies", "15. Network, battery, schedule and bandwidth", "Default Maximum usage applies no transfer restriction. Settings can pause on metered networks, below a battery threshold, or outside a daily schedule. Per-job bandwidth limits constrain rclone traffic. Policies defer work; they do not discard queued changes."),
    ("diagnostics", "16. Logs, health dashboard and diagnostics", "The live log shows application activity. View log opens job-specific rclone logs. The health dashboard combines job state, callbacks/mounts, peer audit events and provider capabilities. Startup/application/crash logs are under ~/.local/state/tuxdrive; transfer logs are under ~/.cache/tuxdrive/logs.\n\nHOW TO REPORT A PROBLEM\nRun tuxdrive --diagnostics and tuxdrive --system-check --json, reproduce once, then attach relevant redacted logs. Never publish OAuth tokens, passwords, invitations, private keys, Onion authorization or bridge secrets."),
    ("settings", "17. Settings and language", "Settings controls login startup, notifications, minimized startup, Nautilus integration, transfer policies, profile migration and updates. The top flag changes English, German, French, Spanish, Arabic or Hebrew and stores the choice. Arabic/Hebrew text is right-to-left without moving controls; provider/rclone diagnostics may remain in their source language."),
    ("uninstall", "18. Removing TuxDrive safely", "Pause jobs and disconnect streaming mounts before uninstalling. Removing a job/account does not delete synchronized content. Uninstall the package with apt remove tuxdrive. Configuration and encrypted credentials remain for reinstall unless deliberately removed. Before deleting ~/.config/tuxdrive, rclone configuration, Secret Service entries or peer identities, export what is needed and understand that encrypted remotes may become inaccessible."),
)

# The translated editions intentionally mirror every English topic and numbered
# procedure. Provider-generated error text can still be English.
_DE = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Überblick", "TuxDrive synchronisiert ausgewählte Ordner mit acht Cloud-Anbietern, stellt Dateien bei Bedarf bereit und verbindet verschlüsselte Peer-Ordner ohne TuxDrive-Inhaltsserver. Links stehen Konten, in der Mitte Aufträge und unten das Aktivitätsprotokoll.\n\nSCHNELLSTART\n1. Konto verbinden. 2. Synchronisierten Ordner oder Streaming-Laufwerk hinzufügen. 3. Cloud-/lokalen Pfad, Richtung und Schutz prüfen. 4. Vor der ersten Zwei-Wege-Synchronisierung unabhängig sichern."),
    ("accounts", "2. Cloud-Konten und Anmeldung", "Über + oder Konto verbinden: Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive oder Nextcloud. OAuth öffnet die Anbieter-Webseite; TuxDrive erhält das Passwort nicht. Proton kann einen separaten 2FA-Code verlangen. Zugangsdaten liegen in der verschlüsselten rclone-Konfiguration mit Secret Service.\n\nREPARATUR\nKontomenü → Anmeldedaten erneuern, Autorisierung abschließen und Cloud-Prüfung abwarten."),
    ("selective", "3. Ordnerauswahl und Cloud-Bereiche", "Der visuelle Baum lädt Ordner bei Bedarf. Mehrere Ordner oder das ganze Laufwerk können markiert werden. Google trennt Meine Ablage, Für mich freigegeben und geteilte Ablagen. Über Bearbeiten Auswahl/Pfade ändern und gefährliche Überschneidungen vermeiden."),
    ("sync", "4. Synchronisierungsarten und Rückrufe", "Zwei Wege überträgt Erstellen, Ändern, Verschieben und Löschen in beide Richtungen. Nur Download/Empfangen schützt die Cloud; nur Upload/Senden schützt lokal. Rückrufe übertragen gespeicherte lokale Änderungen, Polling erkennt Remote-Änderungen. Jetzt synchronisieren startet, Stoppen bricht ab, der Schalter pausiert Automatik."),
    ("streaming", "5. Dateien bei Bedarf und Offline-Nutzung", "Streaming bindet die Cloud-Struktur über FUSE ein; Dateiinhalte kommen erst beim Öffnen. Der Einhängeordner muss leer sein. In Nautilus kann ein Element offline behalten oder wieder nur online gesetzt werden. Vor dem Löschen des Ordners sauber trennen."),
    ("actions", "6. Auftragsaktionen", "Ordner öffnen öffnet lokal; Online öffnen den genauen Cloud-Ordner; Link teilen kopiert einen Anbieterlink. Umbenennen ändert nur die Anzeige. Bearbeiten ändert Pfade/Modus/Filter. Protokoll zeigt Details. Papierkorb entfernt nur die Definition, keine Daten."),
    ("safety", "7. Verlauf, Wiederherstellung und Schutz", "Verlauf stellt lokale Versionen/Papierkorb wieder her. Prüfen vergleicht beide Seiten; Konflikte verlangt eine Entscheidung. Massenänderungs-/Ransomware-Schutz pausiert verdächtige Löschungen oder Endungen. Auftrag stoppen, Protokoll prüfen, gute Version wiederherstellen, beide Seiten verifizieren, dann fortsetzen."),
    ("exceptions", "8. Ausnahmen und Konflikte", "Ausnahmen sind anklickbare Regeln für temporäre/Sperrdateien oder geprüfte Fehlerpfade und können wieder entfernt werden. Unsichere Google-Downloads brauchen ausdrückliche Zustimmung. Bei Unsicherheit Konfliktregel Beide behalten verwenden."),
    ("peer", "9. Private Peer-Ordner", "Peer-Freigabe nutzt authentifiziertes, hostschlüsselgebundenes SFTP und einzelne Geräteschlüssel. Host wählt Ordner/Adresse/Port/autorisierte Geräte; Gast importiert Einladung/QR und prüft Fingerabdruck. Rollen: Lesen/Schreiben, nur Lesen, nur Senden, nur Empfangen. Verlorenes Gerät widerrufen und Freigabe neu starten."),
    ("privacy", "10. Tor und Fail-closed", "Optionaler Tor-v3-Onion-Service mit dauerhafter Identität und Geräteautorisierung. Richtlinien Tor-only, Direct-only, kein Relay, keine öffentliche IP und keine Provider-Cloud pausieren bei Verstoß statt still zurückzufallen. Einladung privat verteilen und prüfen, dass keine verbotenen Endpunkte enthalten sind."),
    ("collaboration", "11. Gemeinsame Dokumente", "Markdown/Text verwendet CRDT-Operationen für Offline-Bearbeitung und deterministische Zusammenführung. Zustand liegt separat in .tuxdrive-collaboration; Export erzeugt eine normale Datei. Verschlüsselte kurzlebige Präsenz, Kommentare, Vorschläge, Freigaben und Aufgaben sind möglich. ODT/ODS ist experimentell; DOCX/XLSX/PDF bleibt Sperre/Version/Review."),
    ("profile", "12. Verschlüsseltes Profil und Umzug", "Profil/Migration verschlüsselt Konfiguration lokal per AES-256-GCM/scrypt und speichert sie beim gewählten OAuth-Anbieter. Zugangsdaten/private Peer-Schlüssel sind standardmäßig ausgeschlossen. Auf neuem Gerät gleichen Anbieter verbinden, Backup prüfen/wiederherstellen, Konten neu autorisieren und Pfade prüfen."),
    ("nautilus", "13. Nautilus-Integration", "Nautilus zeigt Embleme für synchronisiert, aktiv, ausstehend, pausiert, Fehler und Streaming sowie Kontextaktionen. Bei Konflikten in Einstellungen deaktivieren und Nautilus neu starten."),
    ("updates", "14. Sichere Updates", "Update prüft signiertes, ablaufendes Manifest, Ed25519, URL, SHA-256, Paketname/-version und Größe vor PolicyKit. Prüfung starten, Hinweise lesen, herunterladen/installieren, Systemabfrage bestätigen und TuxDrive neu starten. Fehler verändert die Installation nicht."),
    ("policies", "15. Netzwerk, Akku, Zeit und Bandbreite", "Maximale Nutzung ist uneingeschränkt. Optional bei getaktetem Netz, niedrigem Akku oder außerhalb des Zeitfensters pausieren. Bandbreite pro Auftrag begrenzen. Aufgeschobene Änderungen gehen nicht verloren."),
    ("diagnostics", "16. Protokolle und Diagnose", "Live-Protokoll zeigt Aktivität; Auftragsprotokolle liegen unter ~/.cache/tuxdrive/logs, Start/App/Crash unter ~/.local/state/tuxdrive. Problem melden: tuxdrive --diagnostics und --system-check --json ausführen, einmal reproduzieren, Logs schwärzen. Niemals Token, Passwörter, private Schlüssel oder Onion-/Bridge-Geheimnisse senden."),
    ("settings", "17. Einstellungen und Sprache", "Einstellungen: Autostart, Benachrichtigungen, Nautilus, Übertragungsrichtlinien, Profil und Updates. Die Flagge wechselt Englisch, Deutsch, Französisch, Spanisch, Arabisch oder Hebräisch. Arabisch/Hebräisch wird rechts nach links dargestellt, ohne die Anordnung der Bedienelemente zu ändern."),
    ("uninstall", "18. Sicher entfernen", "Aufträge pausieren und Streaming trennen. apt remove tuxdrive entfernt das Paket, nicht automatisch Inhalte/Konfiguration. Vor dem Löschen von Konfiguration, Secret-Service-Einträgen oder Peer-Identitäten exportieren; sonst können verschlüsselte Daten unzugänglich werden."),
))

_FR = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Présentation", "TuxDrive synchronise des dossiers avec huit fournisseurs, monte les fichiers à la demande et relie des dossiers pair-à-pair chiffrés sans serveur de contenu TuxDrive. Comptes à gauche, tâches au centre, activité en bas.\n\nDÉMARRAGE\n1. Connectez un compte. 2. Ajoutez un dossier ou lecteur streaming. 3. Vérifiez chemins, sens et protections. 4. Gardez une sauvegarde indépendante avant la première synchronisation bidirectionnelle."),
    ("accounts", "2. Comptes et authentification", "Utilisez + pour Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive ou Nextcloud. OAuth ouvre le site du fournisseur; TuxDrive ne reçoit pas le mot de passe. Proton peut demander un code 2FA séparé. Les secrets sont dans la configuration rclone chiffrée protégée par Secret Service. Réparer via menu du compte → Actualiser les identifiants."),
    ("selective", "3. Sélection des dossiers", "L’arbre visuel charge les dossiers à la demande. Cochez plusieurs dossiers ou tout le lecteur. Google sépare Mon Drive, Partagés avec moi et les Drives partagés. Modifier permet de changer l’emplacement et d’éviter les chevauchements locaux dangereux."),
    ("sync", "4. Modes de synchronisation", "Bidirectionnel propage créations, modifications, déplacements et suppressions. Réception seule protège le cloud; envoi seul protège le local. Les rappels traitent les sauvegardes locales, le sondage détecte le distant. Synchroniser lance, Arrêter annule, l’interrupteur suspend l’automatique."),
    ("streaming", "5. Fichiers à la demande", "Le streaming monte l’arborescence avec FUSE; le contenu arrive à l’ouverture. Le point de montage doit être vide. Dans Nautilus, conservez un élément hors ligne ou remettez-le en ligne uniquement. Déconnectez avant de supprimer le montage."),
    ("actions", "6. Actions d’une tâche", "Ouvrir dossier ouvre le local; Ouvrir en ligne cible le dossier cloud; Lien de partage copie un lien. Renommer change seulement l’étiquette. Modifier change chemins/mode/filtres. Journal affiche les détails. La corbeille retire la définition sans supprimer les données."),
    ("safety", "7. Historique, récupération et protection", "Historique restaure versions et suppressions recyclées. Vérifier compare les côtés; Conflits exige une décision. La protection contre changements massifs/ransomware suspend les rafales suspectes. Arrêtez, lisez le journal, restaurez une version saine, vérifiez puis reprenez."),
    ("exceptions", "8. Exceptions et conflits", "Les exceptions sont des règles cliquables pour fichiers temporaires/verrouillés ou chemins problématiques vérifiés. Supprimez la règle pour réinclure. Les téléchargements Google signalés exigent un accord explicite. En cas de doute, conservez les deux copies."),
    ("peer", "9. Dossiers pair-à-pair privés", "Partage via SFTP authentifié avec clé d’hôte épinglée et clés par appareil. L’hôte choisit dossier/adresse/port/appareils; l’invité importe invitation/QR et vérifie l’empreinte. Rôles lecture-écriture, lecture, envoi ou réception. Révoquez immédiatement un appareil perdu."),
    ("privacy", "10. Tor et politique fermée", "Service Onion v3 optionnel, persistant et autorisé par appareil. Tor uniquement, direct uniquement, sans relais, sans IP publique et jamais de cloud fournisseur suspendent plutôt que revenir silencieusement. Distribuez l’invitation en privé."),
    ("collaboration", "11. Documents collaboratifs", "Markdown/texte utilise un CRDT pour édition hors ligne et convergence déterministe. L’état reste dans .tuxdrive-collaboration; Export produit un fichier normal. Présence chiffrée éphémère, commentaires, suggestions, validations et tâches. ODT/ODS expérimental; DOCX/XLSX/PDF reste verrou/version/revue."),
    ("profile", "12. Profil chiffré et migration", "Profil/migration chiffre localement par AES-256-GCM/scrypt et stocke chez le fournisseur OAuth choisi. Identifiants et clés privées sont exclus par défaut. Sur le nouvel appareil, connectez le même fournisseur, inspectez/restaurez, réautorisez puis vérifiez chaque chemin."),
    ("nautilus", "13. Intégration Nautilus", "Nautilus affiche les emblèmes synchronisé, actif, attente, pause, erreur et streaming, plus les actions contextuelles. Désactivez dans Paramètres en cas de conflit et redémarrez Nautilus."),
    ("updates", "14. Mises à jour sûres", "Le contrôle vérifie manifeste signé/expirant, Ed25519, URL, SHA-256, identité/version du paquet et taille avant PolicyKit. Vérifiez, lisez les notes, téléchargez/installez, autorisez puis redémarrez. Un échec laisse la version actuelle intacte."),
    ("policies", "15. Réseau, batterie, horaire et débit", "Utilisation maximale n’impose aucune limite. Suspendez sur réseau facturé, batterie faible ou hors plage horaire; limitez le débit par tâche. Les changements différés restent en attente."),
    ("diagnostics", "16. Journaux et diagnostic", "Activité en direct; journaux de tâche sous ~/.cache/tuxdrive/logs; démarrage/application/crash sous ~/.local/state/tuxdrive. Pour signaler: tuxdrive --diagnostics et --system-check --json, reproduire une fois, masquer les secrets. Ne partagez jamais jetons, mots de passe, invitations ou clés privées."),
    ("settings", "17. Paramètres et langue", "Paramètres gère démarrage, notifications, Nautilus, politiques, profil et mises à jour. Le drapeau choisit anglais, allemand, français, espagnol, arabe ou hébreu. Arabe et hébreu s’affichent de droite à gauche sans déplacer les commandes; les diagnostics peuvent rester dans leur langue source."),
    ("uninstall", "18. Désinstallation sûre", "Suspendez et déconnectez les montages. apt remove tuxdrive retire le paquet, pas les contenus ni forcément la configuration. Exportez avant de supprimer configuration, Secret Service ou identités pair; les données chiffrées pourraient devenir inaccessibles."),
))

_ES = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Descripción general", "TuxDrive sincroniza carpetas con ocho proveedores, monta archivos bajo demanda y conecta carpetas cifradas entre pares sin servidor de contenido TuxDrive. Cuentas a la izquierda, trabajos en el centro y actividad abajo.\n\nINICIO\n1. Conecte una cuenta. 2. Añada carpeta o unidad streaming. 3. Revise rutas, dirección y protección. 4. Mantenga una copia independiente antes de la primera sincronización bidireccional."),
    ("accounts", "2. Cuentas y autenticación", "Use + para Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive o Nextcloud. OAuth abre la web del proveedor; TuxDrive no recibe la contraseña. Proton puede pedir 2FA aparte. Los secretos están en rclone cifrado protegido por Secret Service. Repare desde menú de cuenta → Actualizar credenciales."),
    ("selective", "3. Selección de carpetas", "El árbol visual carga carpetas al expandir. Marque varias o toda la unidad. Google separa Mi unidad, Compartido conmigo y unidades compartidas. Editar cambia ubicación y ayuda a evitar solapamientos locales peligrosos."),
    ("sync", "4. Modos de sincronización", "Bidireccional propaga creación, cambios, movimientos y borrado. Solo recepción protege cloud; solo envío protege local. Callbacks procesan guardados locales y sondeo detecta remoto. Sincronizar inicia, Detener cancela y el interruptor pausa lo automático."),
    ("streaming", "5. Archivos bajo demanda", "Streaming monta la estructura con FUSE; el contenido baja al abrir. El punto debe estar vacío. En Nautilus mantenga un elemento sin conexión o devuélvalo a solo en línea. Desconecte antes de borrar el montaje."),
    ("actions", "6. Acciones del trabajo", "Abrir carpeta abre local; Abrir en línea va a la carpeta cloud; Compartir enlace copia un vínculo. Renombrar cambia solo la etiqueta. Editar cambia rutas/modo/filtros. Registro muestra detalles. Papelera elimina la definición, no los datos."),
    ("safety", "7. Historial, recuperación y protección", "Historial restaura versiones y reciclaje. Verificar compara; Conflictos exige decisión. Protección masiva/ransomware pausa ráfagas sospechosas. Detenga, revise registro, restaure versión sana, verifique ambos lados y reanude."),
    ("exceptions", "8. Excepciones y conflictos", "Las excepciones son reglas pulsables para temporales/bloqueos o rutas problemáticas verificadas; elimínelas para incluir de nuevo. Google marcado requiere aceptación explícita. Si duda, conserve ambas copias."),
    ("peer", "9. Carpetas privadas entre pares", "SFTP autenticado con clave de host fijada e identidad por dispositivo. El host elige carpeta/dirección/puerto/dispositivos; invitado importa invitación/QR y verifica huella. Roles lectura-escritura, solo lectura, envío o recepción. Revoque un dispositivo perdido."),
    ("privacy", "10. Tor y cierre seguro", "Servicio Onion v3 opcional, persistente y con autorización por dispositivo. Solo Tor, solo directo, sin relay, sin IP pública y nunca cloud detienen el tráfico, sin fallback silencioso. Distribuya la invitación en privado."),
    ("collaboration", "11. Documentos colaborativos", "Markdown/texto usa CRDT para editar offline y converger. Estado separado en .tuxdrive-collaboration; Exportar crea archivo normal. Presencia cifrada temporal, comentarios, sugerencias, aprobaciones y tareas. ODT/ODS experimental; DOCX/XLSX/PDF usa bloqueo/versiones/revisión."),
    ("profile", "12. Perfil cifrado y migración", "Perfil/migración cifra localmente con AES-256-GCM/scrypt y guarda en el proveedor OAuth elegido. Credenciales y claves privadas se excluyen por defecto. En el nuevo equipo conecte el mismo proveedor, inspeccione/restaure, reautorice y verifique rutas."),
    ("nautilus", "13. Integración con Nautilus", "Nautilus muestra emblemas sincronizado, activo, pendiente, pausa, error y streaming, además de acciones. Desactive en Configuración si hay conflicto y reinicie Nautilus."),
    ("updates", "14. Actualizaciones seguras", "Comprueba manifiesto firmado/caducable, Ed25519, URL, SHA-256, identidad/versión y tamaño antes de PolicyKit. Compruebe, lea notas, descargue/instale, autorice y reinicie. Un fallo deja intacta la instalación."),
    ("policies", "15. Red, batería, horario y ancho de banda", "Uso máximo no restringe. Puede pausar en red medida, batería baja o fuera de horario y limitar ancho de banda por trabajo. Los cambios aplazados no se pierden."),
    ("diagnostics", "16. Registros y diagnóstico", "Actividad en directo; registros de trabajos en ~/.cache/tuxdrive/logs y arranque/app/crash en ~/.local/state/tuxdrive. Para informar ejecute tuxdrive --diagnostics y --system-check --json, reproduzca una vez y oculte secretos. Nunca publique tokens, contraseñas, invitaciones ni claves privadas."),
    ("settings", "17. Configuración e idioma", "Configuración controla inicio, avisos, Nautilus, políticas, perfil y actualizaciones. La bandera selecciona inglés, alemán, francés, español, árabe o hebreo. Árabe y hebreo se muestran de derecha a izquierda sin mover los controles; los diagnósticos pueden conservar su idioma original."),
    ("uninstall", "18. Desinstalación segura", "Pause trabajos y desconecte montajes. apt remove tuxdrive quita el paquete, no los datos ni siempre la configuración. Exporte antes de borrar configuración, Secret Service o identidades; datos cifrados podrían quedar inaccesibles."),
))

_AR = tuple((key, title, body) for (key, title, body) in (
    ("overview", "١. نظرة عامة على TuxDrive", "يزامن TuxDrive المجلدات المختارة مع ثمانية مزودين، ويعرض الملفات عند الطلب، ويربط مجلدات مشفرة بين الأجهزة دون تخزينها على خادم TuxDrive. للبدء: اربط حسابًا، أضف مجلدًا أو محرك بث، راجع المسارات والاتجاه والحماية، واحتفظ بنسخة احتياطية مستقلة قبل أول مزامنة ثنائية الاتجاه."),
    ("accounts", "٢. الحسابات والمصادقة", "استخدم زر الإضافة لربط Google Drive أو OneDrive أو Dropbox أو Box أو pCloud أو MEGA أو Proton Drive أو Nextcloud. يفتح OAuth موقع المزود ولا يرى TuxDrive كلمة المرور. لإصلاح الدخول افتح قائمة الحساب واختر إعادة الربط، ثم أكمل التحقق السحابي."),
    ("selective", "٣. اختيار المجلدات والمواقع", "تُحمّل شجرة المجلدات بصريًا عند توسيعها. اختر مجلدًا واحدًا أو أكثر أو المحرك كله. يفصل Google بين ملفاتي والمشترك معي والمحركات المشتركة. لتغيير الاختيار افتح تحرير، راجع الموقع والمسارات المحلية وتجنب التداخل غير الآمن ثم احفظ."),
    ("sync", "٤. أوضاع المزامنة والاستدعاءات", "تنقل المزامنة الثنائية الإنشاء والتعديل والنقل والحذف في الاتجاهين. يحمي وضع التنزيل فقط السحابة ويحمي الرفع فقط الجانب المحلي. استخدم مزامنة الآن للتشغيل وإيقاف للإلغاء والمفتاح الصغير لتعليق العمل التلقائي، وافحص السجل قبل أي استرداد قسري."),
    ("streaming", "٥. الملفات عند الطلب والعمل دون اتصال", "يركب وضع البث بنية السحابة بواسطة FUSE وتُنزل محتويات الملف عند فتحه. يجب أن يكون موضع التركيب فارغًا. أضف محرك بث واختر الشجرة والموضع ثم ابدأ البث؛ ومن Nautilus اختر الاحتفاظ دون اتصال أو العودة إلى الإنترنت فقط، وافصل التركيب بأمان قبل حذفه."),
    ("actions", "٦. أزرار المهمة والمجلد عبر الإنترنت", "فتح المجلد يفتح الوجهة المحلية وفتح عبر الإنترنت يفتح مجلد المزود المحدد عند دعمه. مشاركة رابط تنشئ رابطًا، وإعادة التسمية تغير الاسم المعروض فقط، والتحرير يغير المسارات والوضع والفلاتر. تعرض السجلات التفاصيل، بينما تحذف سلة المهملات تعريف المهمة لا البيانات."),
    ("safety", "٧. الاسترداد والإصدارات والحماية", "يعيد السجل الإصدارات والملفات المحذوفة محليًا، ويقارن التحقق الجانبين، ويعرض مركز التعارضات القرارات المطلوبة. توقف حماية التغيير الجماعي وبرامج الفدية العمليات المشبوهة. عند مشكلة أوقف المهمة، راجع السجل، استعد نسخة سليمة، تحقق من الجانبين ثم استأنف."),
    ("exceptions", "٨. الاستثناءات والتعارضات", "الاستثناءات قواعد قابلة للنقر للملفات المؤقتة أو المقفلة والمسارات التي راجعتها. احذف القاعدة لإعادة تضمين المسار. يتطلب ملف Google المصنف خطرًا موافقة صريحة. عند الشك اختر الاحتفاظ بالنسختين بدل استبدال إحداهما تلقائيًا."),
    ("peer", "٩. المجلدات الخاصة بين الأجهزة", "تستخدم المشاركة SFTP موثقًا مع تثبيت مفتاح المضيف وهوية منفصلة لكل جهاز. يحدد المضيف المجلد والعنوان والأجهزة المسموحة، ويستورد الضيف الدعوة أو QR ويتحقق من البصمة. تبادل المفاتيح عبر قناة موثوقة، وراجع الدور، وألغِ جهازًا مفقودًا فورًا."),
    ("privacy", "١٠. Tor وسياسات الإغلاق الآمن", "يمكن نشر مساحة العمل كخدمة Onion v3 مع تفويض عميل لكل جهاز. تشمل السياسات Tor فقط أو مباشر فقط أو دون ترحيل أو دون اكتشاف IP عام أو دون سحابة. أي مخالفة توقف النقل ولا تستخدم اتصالًا بديلًا بصمت. وزع الدعوة وبيانات التفويض بصورة خاصة."),
    ("collaboration", "١١. المستندات التعاونية", "يستخدم Markdown والنص CRDT للعمل دون اتصال والاندماج الحتمي، وتبقى الحالة منفصلة في .tuxdrive-collaboration بينما يكتب تصدير نقطة فحص ملفًا عاديًا. الحضور المشفر مؤقت والتعليقات والموافقات مهام مراجعة. دعم ODT وODS تجريبي، أما DOCX وXLSX وPDF فتستخدم القفل والإصدارات."),
    ("profile", "١٢. النسخ الاحتياطي المشفر والترحيل", "تشفّر أداة الملف الشخصي الإعدادات محليًا بواسطة AES-256-GCM وscrypt وتحفظها لدى مزود OAuth مختار. تُستبعد بيانات الاعتماد والمفاتيح الخاصة افتراضيًا. على الجهاز الجديد اربط المزود نفسه، افحص النسخة، استعدها، أعد تفويض الحسابات وتحقق من كل مسار قبل التفعيل."),
    ("nautilus", "١٣. تكامل Nautilus", "يعرض Nautilus شارات متزامن وقيد المزامنة ومعلق ومتوقف وخطأ وبث، إضافة إلى إجراءات السياق للمزامنة وفتح السحابة والسجل والتوفر دون اتصال. إذا تعارض الامتداد مع إضافة أخرى عطله من الإعدادات ثم أعد تشغيل Nautilus."),
    ("updates", "١٤. التحديثات الآمنة", "يتحقق فحص التحديث من بيان موقع ومحدد الصلاحية وتوقيع Ed25519 وعنوان المستودع وSHA-256 وهوية الحزمة وإصدارها قبل طلب صلاحية المدير. اختر فحص، راجع الملاحظات، نزّل وثبّت ثم أعد التشغيل. فشل التحقق يترك النسخة الحالية دون تغيير."),
    ("policies", "١٥. الشبكة والبطارية والجدول", "لا يفرض وضع الاستخدام الأقصى أي قيود افتراضيًا. يمكن تعليق النقل على شبكة محسوبة أو عند انخفاض البطارية أو خارج الجدول اليومي، كما يمكن تحديد السرعة لكل مهمة. تؤجل هذه السياسات العمل ولا تحذف التغييرات المنتظرة."),
    ("diagnostics", "١٦. السجلات والتشخيص", "يعرض السجل المباشر نشاط التطبيق وتوجد سجلات المهام في ~/.cache/tuxdrive/logs وسجلات البدء والتعطل في ~/.local/state/tuxdrive. للإبلاغ شغّل tuxdrive --diagnostics وtuxdrive --system-check --json وأخفِ الأسرار. لا تنشر الرموز أو كلمات المرور أو الدعوات أو المفاتيح الخاصة."),
    ("settings", "١٧. الإعدادات واللغة", "تتحكم الإعدادات في بدء الدخول والإشعارات وNautilus وسياسات النقل والملف الشخصي والتحديثات. يبدل العلم في الشريط العلوي الإنجليزية والألمانية والفرنسية والإسبانية والعربية والعبرية ويحفظ الاختيار. يظهر النص العربي والعبراني من اليمين إلى اليسار دون تغيير ترتيب الواجهة."),
    ("uninstall", "١٨. إزالة TuxDrive بأمان", "أوقف المهام وافصل محركات البث قبل الإزالة. يحذف apt remove tuxdrive الحزمة ولا يحذف بالضرورة البيانات أو الإعدادات. صدّر نسخة قبل حذف الإعداد أو Secret Service أو هويات الأجهزة، لأن فقد كلمة مرور أو مفتاح قد يجعل البيانات المشفرة غير قابلة للاسترداد."),
))

_HE = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. סקירה כללית של TuxDrive", "TuxDrive מסנכרן תיקיות נבחרות עם שמונה ספקים, מציג קבצים לפי דרישה ומחבר תיקיות עמיתים מוצפנות בלי לאחסן אותן בשרת TuxDrive. להתחלה: חברו חשבון, הוסיפו תיקייה או כונן הזרמה, בדקו נתיבים, כיוון והגנות ושמרו גיבוי עצמאי לפני הסנכרון הדו־כיווני הראשון."),
    ("accounts", "2. חשבונות ואימות", "השתמשו בכפתור ההוספה עבור Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive או Nextcloud. OAuth פותח את אתר הספק ו-TuxDrive אינו מקבל את הסיסמה. לתיקון הרשאה פתחו את תפריט החשבון, בחרו רענון הרשאות והמתינו לאימות הגישה לענן."),
    ("selective", "3. בחירת תיקיות ומיקומי ענן", "עץ התיקיות נטען כאשר מרחיבים ענפים. אפשר לבחור תיקייה אחת, כמה תיקיות או את כל הכונן. Google מפריד בין הכונן שלי, משותף איתי וכוננים משותפים. לשינוי הבחירה פתחו עריכה, בדקו את המיקום והיעדים המקומיים, מנעו חפיפה מסוכנת ושמרו."),
    ("sync", "4. מצבי סנכרון וקריאות שינוי", "סנכרון דו־כיווני מעביר יצירה, שינוי, העברה ומחיקה בשני הכיוונים. קבלה בלבד מגנה על הענן ושליחה בלבד מגנה על הצד המקומי. סנכרון עכשיו מפעיל, עצירה מבטלת והמתג משהה עבודה אוטומטית. בדקו מצב ויומן לפני שחזור כפוי."),
    ("streaming", "5. קבצים לפי דרישה וזמינות לא מקוונת", "כונן הזרמה מעגן את מבנה הענן באמצעות FUSE ומוריד תוכן כשפותחים קובץ. נקודת העיגון חייבת להיות ריקה. הוסיפו כונן הזרמה, בחרו ענף ויעד והפעילו; ב-Nautilus אפשר לשמור פריט לא מקוון או להחזירו למצב מקוון בלבד. נתקו לפני מחיקת העיגון."),
    ("actions", "6. פעולות משימה ותיקייה מקוונת", "פתיחת תיקייה מציגה את היעד המקומי ופתיחה בענן מציגה את תיקיית הספק המדויקת כאשר נתמך. שיתוף קישור יוצר קישור, שינוי שם משנה רק את התווית, ועריכה משנה נתיבים, מצב ומסננים. היומן מציג פרטים וסל המחזור מסיר את הגדרת המשימה, לא את הנתונים."),
    ("safety", "7. שחזור, גרסאות והגנה", "היסטוריה משחזרת גרסאות ומחיקות מקומיות, אימות משווה בין הצדדים ומרכז התנגשויות דורש החלטה מפורשת. הגנת שינוי המוני וכופרה משהה פעילות חשודה. במקרה בעיה עצרו, בדקו יומן, שחזרו גרסה תקינה, אמתו את שני הצדדים ורק אז המשיכו."),
    ("exceptions", "8. חריגים והתנגשויות", "חריגי סנכרון הם כללים לחיצים עבור קבצים זמניים, קבצי נעילה או נתיב בעייתי שנבדק. הסירו כלל כדי לכלול את הנתיב שוב. קובץ Google שסומן כמסוכן דורש אישור מפורש. אם אינכם בטוחים בחרו לשמור את שני העותקים."),
    ("peer", "9. תיקיות עמיתים פרטיות", "שיתוף עמיתים משתמש ב-SFTP מאומת, הצמדת מפתח מארח וזהות נפרדת לכל התקן. המארח בוחר תיקייה, כתובת והתקנים מורשים; האורח מייבא הזמנה או QR ומאמת טביעת מפתח. החליפו מפתחות בערוץ מהימן, בדקו תפקיד ובטלו מיד התקן שאבד."),
    ("privacy", "10. Tor ומדיניות כשל סגור", "מרחב עבודה יכול לפרסם שירות Onion v3 עם הרשאת לקוח נפרדת לכל התקן. המדיניות כוללת Tor בלבד, ישיר בלבד, ללא ממסר, ללא גילוי IP ציבורי ולעולם ללא ענן ספק. הפרה משהה תעבורה בלי נסיגה שקטה לחיבור אחר. העבירו הזמנות והרשאות באופן פרטי."),
    ("collaboration", "11. מסמכים שיתופיים", "Markdown וטקסט משתמשים ב-CRDT לעריכה לא מקוונת והתכנסות דטרמיניסטית. המצב נשמר בנפרד תחת .tuxdrive-collaboration וייצוא נקודת ביקורת יוצר קובץ רגיל. נוכחות מוצפנת היא זמנית; הערות ואישורים הם אירועי ביקורת. ODT ו-ODS ניסיוניים, ו-DOCX, XLSX ו-PDF משתמשים בנעילות וגרסאות."),
    ("profile", "12. גיבוי מוצפן והעברת התקן", "כלי הפרופיל מצפין הגדרות מקומית באמצעות AES-256-GCM ו-scrypt ושומר אצל ספק OAuth שנבחר. הרשאות ומפתחות פרטיים אינם נכללים כברירת מחדל. בהתקן החדש חברו אותו ספק, בדקו ושחזרו את הגיבוי, אשרו מחדש חשבונות ובדקו כל נתיב לפני הפעלה."),
    ("nautilus", "13. שילוב Nautilus", "Nautilus מציג סמלים עבור מסונכרן, פעיל, ממתין, מושהה, שגיאה והזרמה, ופעולות לסנכרון, פתיחה בענן, יומן וזמינות לא מקוונת. אם יש התנגשות עם הרחבה אחרת השביתו את השילוב בהגדרות והפעילו מחדש את Nautilus."),
    ("updates", "14. עדכונים מאובטחים", "בדיקת העדכון מאמתת מניפסט חתום ומוגבל בזמן, חתימת Ed25519, כתובת מאושרת, SHA-256, זהות חבילה, גרסה וגודל לפני בקשת הרשאת מנהל. בדקו, קראו הערות, הורידו והתקינו ואז הפעילו מחדש. כשל אימות משאיר את ההתקנה הקיימת ללא שינוי."),
    ("policies", "15. רשת, סוללה, לוח זמנים ורוחב פס", "ברירת המחדל שימוש מרבי אינה מגבילה העברות. אפשר להשהות ברשת מדודה, מתחת לסף סוללה או מחוץ לשעות יומיות ולהגביל רוחב פס לכל משימה. המדיניות דוחה עבודה ואינה מוחקת שינויים ממתינים."),
    ("diagnostics", "16. יומנים ואבחון", "יומן הפעילות מציג עבודה שוטפת; יומני משימה נמצאים ב-~/.cache/tuxdrive/logs ויומני התחלה וקריסה ב-~/.local/state/tuxdrive. לדיווח הריצו tuxdrive --diagnostics ו-tuxdrive --system-check --json והסתירו סודות. אל תפרסמו אסימונים, סיסמאות, הזמנות או מפתחות פרטיים."),
    ("settings", "17. הגדרות ושפה", "ההגדרות שולטות בהפעלה, התראות, Nautilus, מדיניות העברה, פרופיל ועדכונים. הדגל בסרגל העליון מחליף ושומר אנגלית, גרמנית, צרפתית, ספרדית, ערבית או עברית. טקסט עברי וערבי מוצג מימין לשמאל בלי לשנות את מבנה החלון."),
    ("uninstall", "18. הסרה בטוחה של TuxDrive", "השהו משימות ונתקו עיגוני הזרמה לפני הסרה. apt remove tuxdrive מסיר את החבילה אך לא בהכרח נתונים או הגדרות. ייצאו גיבוי לפני מחיקת תצורה, Secret Service או זהויות עמיתים; אובדן סיסמה או מפתח עלול להפוך מידע מוצפן לבלתי ניתן לשחזור."),
))

_TOPICS = {"en": _EN, "de": _DE, "fr": _FR, "es": _ES, "ar": _AR, "he": _HE}


def topics(language: str) -> tuple[HelpTopic, ...]:
    selected = _TOPICS.get(language, _EN)
    return tuple(HelpTopic(*item) for item in selected)
