"""Localized, offline user documentation displayed by the desktop client."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HelpTopic:
    key: str
    title: str
    body: str


_EN = (
    ("overview", "1. TuxDrive overview", "TuxDrive synchronizes selected folders with eight cloud providers and GitHub, mounts files on demand, and connects encrypted peer folders without storing peer data on a TuxDrive server. The left side lists accounts; the center lists jobs grouped into editable internal groups; the bottom log explains current activity. Groups never move local or cloud files. Provider icons identify the storage service and state text/badges show connected, syncing, paused, or error conditions.\n\nHOW TO START\n1. Connect an account. 2. Add a synchronized folder, GitHub repository or streaming drive. 3. Review the remote path, local path, direction and safety settings. 4. Keep an independent backup before the first two-way synchronization."),
    ("accounts", "2. Cloud accounts and authentication", "Use + or Connect account for Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive, Nextcloud, or GitHub. Browser-OAuth providers open their own login page; TuxDrive never receives that password. Proton/MEGA/Nextcloud use guided credentials. GitHub uses system Git with an SSH agent or credential helper; TuxDrive rejects tokens embedded in repository URLs and does not store a GitHub token.\n\nHOW TO REPAIR AUTHORIZATION\nOpen the account menu → Reconnect / refresh credentials. Complete provider authorization, or configure system Git credentials for GitHub. Remove an account only after deleting jobs that use it."),
    ("selective", "3. Folder selection and cloud locations", "The visual tree loads folders lazily. Check one or more folders, expand arrows to browse deeper, or select the entire drive. Google Drive exposes My Drive, Shared with me, and each Shared Drive as separate locations. One selected cloud folder creates one job and local destination.\n\nHOW TO CHANGE SELECTION\nChoose Edit on a job, select the intended drive/location and tree nodes, verify that local destinations do not overlap unsafely, then save."),
    ("sync", "4. Synchronization modes and callbacks", "Two-way sync propagates creations, modifications, moves and deletions in both directions. Download-only/receive-only protects the cloud side; upload-only/send-only protects the local side. Real-time callbacks detect saved local changes and transfer changed paths; polling detects remote changes. Block-delta transfer is used for supported direct peers.\n\nHOW TO RUN OR PAUSE\nSync now starts a run. Stop cancels the active process. The compact switch enables or pauses automatic work. Check the status and View log before forcing recovery after an error."),
    ("streaming", "5. Files on demand and offline availability", "A streaming drive mounts the cloud hierarchy with FUSE. Folder names appear immediately while file bodies download when opened. The mount point must be empty. A streaming child can live inside a normal synchronized tree because TuxDrive excludes that subtree; a streaming parent of another sync is unsafe.\n\nHOW TO USE\nAdd folder → Streaming drive, choose the cloud subtree and empty mount folder, then Start streaming. In Nautilus right-click a streamed item or the drive root and choose Always keep available offline. Blue arrows mean hydration is running; the green check and Available offline text appear only after the complete item is cached. Free local space returns it to online-only. Test pinned files without a network before relying on them."),
    ("actions", "6. Job buttons, groups and online folders", "Open folder opens the local destination. Open online opens the exact provider folder or GitHub branch. Share link copies a provider or GitHub link. Rename changes only the label. Group moves the list entry into an internal group; New group creates one, and group names can be edited or deleted without moving files. Edit changes paths, mode, interval, filters and protection. GitHub two-way jobs automatically commit, fetch, rebase and push; conflicts stop safely. View log opens transfer logs. Trash removes the job definition but not data."),
    ("safety", "7. Recovery, versions, integrity and ransomware protection", "History restores locally retained versions and recycled deletions. Verify compares local/cloud content and offers selected repairs. Conflicts opens mismatches for explicit review. Mass-change/ransomware protection pauses suspicious deletion or extension bursts before propagation; it is a safety boundary, not antivirus. Maximum deletions limits destructive runs.\n\nHOW TO RECOVER\nStop the job, inspect View log and Conflicts, restore a known-good version, verify both sides, then resume. Never approve a mass-change event until the source device is clean."),
    ("exceptions", "8. Exceptions, conflicts and unsafe provider files", "Synchronization exceptions are clickable rules. Add temporary/lock files or a failing path after reviewing the error; remove a rule to include it again. Google files flagged as malware/spam require an explicit unsafe-download acknowledgement. Conflict policy can keep both copies, prefer local, or prefer cloud; keeping both is safest when uncertain."),
    ("peer", "9. Private peer-to-peer folders", "Peer sharing uses authenticated, host-key-pinned SFTP and individual device identity keys. Every authorized device receives a separate port and one-key server endpoint. Read-only/receive-only is server read-only; send-only and one-time drops are rooted in private inboxes and cannot browse the workspace. LAN discovery finds candidates but users must verify fingerprints.\n\nHOW TO PAIR\nExchange public keys through a trusted channel, authorize the named device and role, save/start, copy that device's invitation, verify the fingerprint, then connect. Issue a new invitation after changing a role. Revoke a lost device and restart the share."),
    ("privacy", "10. Tor and fail-closed privacy", "A peer workspace can publish a Tor v3 Onion Service, optionally persistent and protected with per-device client authorization. Policies include Tor only, direct only, no relay, no public-IP discovery, and never use provider cloud. Violations pause traffic instead of falling back silently. Bridges/pluggable transports are advanced settings and secrets are excluded from invitations/logs.\n\nHOW TO USE TOR ONLY\nInstall Tor, choose Tor only, enable Onion Service and optionally client authorization, save/start, then distribute the private invitation securely. Confirm that no direct/relay endpoint appears."),
    ("collaboration", "11. Collaborative documents", "Markdown/text uses a bounded operation CRDT: peers edit offline, immutable operations synchronize, and iterative deterministic merge produces the same text. Collaboration state stays in .tuxdrive-collaboration; Export checkpoint writes an ordinary file. Optional encrypted presence expires without permanent audit storage.\n\nODT/ODS support is experimental. TuxDrive rejects unsafe XML, ZIP bombs, excessive entries/sizes and malformed operation files before editing. DOCX/XLSX/PDF remain under leases, versions and review."),
    ("profile", "12. Encrypted profile backup and migration", "Settings → TuxDrive Profile / migrate encrypts configuration locally with AES-256-GCM/scrypt and stores it in a selected OAuth provider. By default OAuth credentials and peer private keys are excluded. Sensitive inclusion is explicit and requires the same strong password during restore. TuxDrive cannot recover that password.\n\nHOW TO MIGRATE\nBack up on the old device, install TuxDrive on the new device, connect the same provider, inspect the discovered backup, restore, then reauthorize excluded accounts and verify every path before enabling jobs."),
    ("nautilus", "13. Nautilus integration", "When enabled, Nautilus displays synchronized/syncing/pending/paused/error/streaming emblems and context actions for sync, online folder, logs and offline availability. From 0.19.2 the emblems are unbranded and purely functional: green check = synchronized, blue rotation arrows = synchronizing, teal cloud/download = streaming, purple pause = paused, amber clock/diamond = pending, red exclamation/octagon = error. Color, silhouette and symbol all differ. The extension reads a private state file and sends actions to the running application. Disable it in Settings if another extension conflicts, then restart Nautilus."),
    ("updates", "14. Secure in-app updates", "Settings → Check for updates verifies the signed expiring manifest and download. After authorization, a fixed privileged helper independently retrieves the manifest, copies the package into root-only staging and rechecks its SHA-256 and Debian identity before APT runs. A replacement or symlink is refused. Version 0.18.1 uses an original-key-signed bridge to 0.19.1; 0.19.1 and later use the rotated-key v2 channel.\n\nHOW TO UPDATE\nCheck, review notes, download, approve the TuxDrive helper prompt, then restart. Any failed verification leaves the current installation unchanged."),
    ("policies", "15. Network, battery, schedule and bandwidth", "Default Maximum usage applies no transfer restriction. Settings can pause on metered networks, below a battery threshold, or outside a daily schedule. Per-job bandwidth limits constrain rclone traffic. Policies defer work; they do not discard queued changes."),
    ("diagnostics", "16. Logs, health dashboard and diagnostics", "The live log shows application activity. View log opens job-specific rclone logs. The health dashboard combines job state, callbacks/mounts, peer audit events and provider capabilities. Startup/application/crash logs are under ~/.local/state/tuxdrive; transfer logs are under ~/.cache/tuxdrive/logs.\n\nHOW TO REPORT A PROBLEM\nRun tuxdrive --diagnostics and tuxdrive --system-check --json, reproduce once, then attach relevant redacted logs. Never publish OAuth tokens, passwords, invitations, private keys, Onion authorization or bridge secrets."),
    ("settings", "17. Settings and language", "Settings controls login startup, notifications, minimized startup, Nautilus integration, transfer policies, profile migration and updates. The top flag changes English, German, French, Spanish, Arabic or Hebrew and stores the choice. Arabic/Hebrew text is right-to-left without moving controls; provider/rclone diagnostics may remain in their source language."),
    ("uninstall", "18. Removing TuxDrive safely", "Pause jobs and disconnect streaming mounts before uninstalling. Removing a job/account does not delete synchronized content. Uninstall the package with apt remove tuxdrive. Configuration and encrypted credentials remain for reinstall unless deliberately removed. Before deleting ~/.config/tuxdrive, rclone configuration, Secret Service entries or peer identities, export what is needed and understand that encrypted remotes may become inaccessible."),
)

# The translated editions intentionally mirror every English topic and numbered
# procedure. Provider-generated error text can still be English.
_DE = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Überblick", "TuxDrive synchronisiert ausgewählte Ordner mit acht Cloud-Anbietern, stellt Dateien bei Bedarf bereit und verbindet verschlüsselte Peer-Ordner ohne TuxDrive-Inhaltsserver. Links stehen Konten, in der Mitte Aufträge und unten das Aktivitätsprotokoll.\n\nSCHNELLSTART\n1. Konto verbinden. 2. Synchronisierten Ordner oder Streaming-Laufwerk hinzufügen. 3. Cloud-/lokalen Pfad, Richtung und Schutz prüfen. 4. Vor der ersten Zwei-Wege-Synchronisierung unabhängig sichern."),
    ("accounts", "2. Cloud-Konten und Anmeldung", "Über + oder Konto verbinden: Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive, Nextcloud oder GitHub. OAuth öffnet die Anbieter-Webseite; TuxDrive erhält das Passwort nicht. GitHub verwendet System-Git mit SSH-Agent oder Credential Helper; Tokens in Repository-URLs werden abgewiesen und nicht gespeichert.\n\nREPARATUR\nKontomenü → Anmeldedaten erneuern; für GitHub die System-Git-Anmeldung konfigurieren."),
    ("selective", "3. Ordnerauswahl und Cloud-Bereiche", "Der visuelle Baum lädt Ordner bei Bedarf. Mehrere Ordner oder das ganze Laufwerk können markiert werden. Google trennt Meine Ablage, Für mich freigegeben und geteilte Ablagen. Über Bearbeiten Auswahl/Pfade ändern und gefährliche Überschneidungen vermeiden."),
    ("sync", "4. Synchronisierungsarten und Rückrufe", "Zwei Wege überträgt Erstellen, Ändern, Verschieben und Löschen in beide Richtungen. Nur Download/Empfangen schützt die Cloud; nur Upload/Senden schützt lokal. Rückrufe übertragen gespeicherte lokale Änderungen, Polling erkennt Remote-Änderungen. Jetzt synchronisieren startet, Stoppen bricht ab, der Schalter pausiert Automatik."),
    ("streaming", "5. Dateien bei Bedarf und Offline-Nutzung", "Streaming bindet die Cloud-Struktur über FUSE ein; Dateiinhalte kommen erst beim Öffnen. Der Einhängeordner muss leer sein. In Nautilus kann ein Element oder die Laufwerkswurzel offline behalten werden. Blaue Pfeile zeigen den Download; erst der grüne Haken bestätigt die vollständige Offline-Verfügbarkeit. Vor dem Löschen des Ordners sauber trennen."),
    ("actions", "6. Aufträge und Gruppen", "Ordner öffnen öffnet lokal; Online öffnen den Cloud-Ordner oder GitHub-Branch. Gruppe ordnet Einträge in frei benannte interne Gruppen ein, ohne Dateien zu verschieben. GitHub-Zwei-Wege-Aufträge committen, holen, rebasen und pushen automatisch; Konflikte stoppen sicher. Papierkorb entfernt nur die Definition, keine Daten."),
    ("safety", "7. Verlauf, Wiederherstellung und Schutz", "Verlauf stellt lokale Versionen/Papierkorb wieder her. Prüfen vergleicht beide Seiten; Konflikte verlangt eine Entscheidung. Massenänderungs-/Ransomware-Schutz pausiert verdächtige Löschungen oder Endungen. Auftrag stoppen, Protokoll prüfen, gute Version wiederherstellen, beide Seiten verifizieren, dann fortsetzen."),
    ("exceptions", "8. Ausnahmen und Konflikte", "Ausnahmen sind anklickbare Regeln für temporäre/Sperrdateien oder geprüfte Fehlerpfade und können wieder entfernt werden. Unsichere Google-Downloads brauchen ausdrückliche Zustimmung. Bei Unsicherheit Konfliktregel Beide behalten verwenden."),
    ("peer", "9. Private Peer-Ordner", "Jedes autorisierte Gerät erhält einen eigenen Port und Endpunkt mit genau einem Schlüssel. Nur-Lesen/Nur-Empfangen ist serverseitig schreibgeschützt; Nur-Senden und Einmal-Drops sehen ausschließlich ihr privates Postfach. Gerät und Rolle wählen, speichern/starten, gerätespezifische Einladung kopieren, Fingerabdruck prüfen. Verlorenes Gerät sofort widerrufen."),
    ("privacy", "10. Tor und Fail-closed", "Optionaler Tor-v3-Onion-Service mit dauerhafter Identität und Geräteautorisierung. Richtlinien Tor-only, Direct-only, kein Relay, keine öffentliche IP und keine Provider-Cloud pausieren bei Verstoß statt still zurückzufallen. Einladung privat verteilen und prüfen, dass keine verbotenen Endpunkte enthalten sind."),
    ("collaboration", "11. Gemeinsame Dokumente", "Markdown/Text verwendet begrenzte CRDT-Operationen und iterative Zusammenführung. Zustand liegt separat in .tuxdrive-collaboration. ODT/ODS ist experimentell; unsicheres XML, ZIP-Bomben sowie übergroße Archive/Operationsdateien werden abgewiesen. DOCX/XLSX/PDF bleibt Sperre/Version/Review."),
    ("profile", "12. Verschlüsseltes Profil und Umzug", "Profil/Migration verschlüsselt Konfiguration lokal per AES-256-GCM/scrypt und speichert sie beim gewählten OAuth-Anbieter. Zugangsdaten/private Peer-Schlüssel sind standardmäßig ausgeschlossen. Auf neuem Gerät gleichen Anbieter verbinden, Backup prüfen/wiederherstellen, Konten neu autorisieren und Pfade prüfen."),
    ("nautilus", "13. Nautilus-Integration", "Nautilus zeigt Embleme für synchronisiert, aktiv, ausstehend, pausiert, Fehler und Streaming sowie Kontextaktionen. Seit 0.19.2 sind die Abzeichen markenfrei und rein funktional: grüner Haken = synchronisiert, blaue Kreispfeile = aktiv, türkise Wolke mit Pfeil = Streaming, violette Pause = pausiert, orangefarbene Raute mit Uhr = ausstehend und rotes Achteck mit Ausrufezeichen = Fehler. Farbe, Form und Symbol unterscheiden sich. Bei Konflikten in Einstellungen deaktivieren und Nautilus neu starten."),
    ("updates", "14. Sichere Updates", "Desktop und privilegierter TuxDrive-Helfer prüfen das signierte Manifest unabhängig. Der Helfer kopiert in ein nur für root zugängliches Verzeichnis und prüft SHA-256 sowie Debian-Identität vor APT erneut; Austausch und Symlinks werden abgewiesen. Version 0.18.1 nutzt eine mit dem ursprünglichen Schlüssel signierte Brücke zu 0.19.1; ab 0.19.1 gilt der v2-Kanal mit rotiertem Schlüssel. Danach TuxDrive neu starten."),
    ("policies", "15. Netzwerk, Akku, Zeit und Bandbreite", "Maximale Nutzung ist uneingeschränkt. Optional bei getaktetem Netz, niedrigem Akku oder außerhalb des Zeitfensters pausieren. Bandbreite pro Auftrag begrenzen. Aufgeschobene Änderungen gehen nicht verloren."),
    ("diagnostics", "16. Protokolle und Diagnose", "Live-Protokoll zeigt Aktivität; Auftragsprotokolle liegen unter ~/.cache/tuxdrive/logs, Start/App/Crash unter ~/.local/state/tuxdrive. Problem melden: tuxdrive --diagnostics und --system-check --json ausführen, einmal reproduzieren, Logs schwärzen. Niemals Token, Passwörter, private Schlüssel oder Onion-/Bridge-Geheimnisse senden."),
    ("settings", "17. Einstellungen und Sprache", "Einstellungen: Autostart, Benachrichtigungen, Nautilus, Übertragungsrichtlinien, Profil und Updates. Die Flagge wechselt Englisch, Deutsch, Französisch, Spanisch, Arabisch oder Hebräisch. Arabisch/Hebräisch wird rechts nach links dargestellt, ohne die Anordnung der Bedienelemente zu ändern."),
    ("uninstall", "18. Sicher entfernen", "Aufträge pausieren und Streaming trennen. apt remove tuxdrive entfernt das Paket, nicht automatisch Inhalte/Konfiguration. Vor dem Löschen von Konfiguration, Secret-Service-Einträgen oder Peer-Identitäten exportieren; sonst können verschlüsselte Daten unzugänglich werden."),
))

_FR = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Présentation", "TuxDrive synchronise des dossiers avec huit fournisseurs, monte les fichiers à la demande et relie des dossiers pair-à-pair chiffrés sans serveur de contenu TuxDrive. Comptes à gauche, tâches au centre, activité en bas.\n\nDÉMARRAGE\n1. Connectez un compte. 2. Ajoutez un dossier ou lecteur streaming. 3. Vérifiez chemins, sens et protections. 4. Gardez une sauvegarde indépendante avant la première synchronisation bidirectionnelle."),
    ("accounts", "2. Comptes et authentification", "Utilisez + pour Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive, Nextcloud ou GitHub. OAuth ouvre le site du fournisseur. GitHub utilise Git système avec agent SSH ou gestionnaire d’identifiants; les jetons intégrés aux URL sont refusés et ne sont pas stockés."),
    ("selective", "3. Sélection des dossiers", "L’arbre visuel charge les dossiers à la demande. Cochez plusieurs dossiers ou tout le lecteur. Google sépare Mon Drive, Partagés avec moi et les Drives partagés. Modifier permet de changer l’emplacement et d’éviter les chevauchements locaux dangereux."),
    ("sync", "4. Modes de synchronisation", "Bidirectionnel propage créations, modifications, déplacements et suppressions. Réception seule protège le cloud; envoi seul protège le local. Les rappels traitent les sauvegardes locales, le sondage détecte le distant. Synchroniser lance, Arrêter annule, l’interrupteur suspend l’automatique."),
    ("streaming", "5. Fichiers à la demande", "Le streaming monte l’arborescence avec FUSE; le contenu arrive à l’ouverture. Dans Nautilus, gardez un élément ou la racine hors ligne. Les flèches bleues indiquent le téléchargement; seule la coche verte confirme la disponibilité complète. Déconnectez avant de supprimer le montage."),
    ("actions", "6. Tâches et groupes", "Ouvrir en ligne cible le dossier cloud ou la branche GitHub. Groupe classe les entrées dans des groupes internes renommables sans déplacer de fichiers. Un travail GitHub bidirectionnel valide, récupère, rebase et pousse automatiquement; un conflit arrête l’opération. La corbeille retire la définition sans supprimer les données."),
    ("safety", "7. Historique, récupération et protection", "Historique restaure versions et suppressions recyclées. Vérifier compare les côtés; Conflits exige une décision. La protection contre changements massifs/ransomware suspend les rafales suspectes. Arrêtez, lisez le journal, restaurez une version saine, vérifiez puis reprenez."),
    ("exceptions", "8. Exceptions et conflits", "Les exceptions sont des règles cliquables pour fichiers temporaires/verrouillés ou chemins problématiques vérifiés. Supprimez la règle pour réinclure. Les téléchargements Google signalés exigent un accord explicite. En cas de doute, conservez les deux copies."),
    ("peer", "9. Dossiers pair-à-pair privés", "Chaque appareil autorisé reçoit un port et un point SFTP à clé unique. Lecture/réception est en lecture seule côté serveur; envoi et dépôt ponctuel ne voient que leur boîte privée. Choisissez appareil/rôle, enregistrez/démarrez, copiez son invitation et vérifiez l’empreinte. Révoquez immédiatement un appareil perdu."),
    ("privacy", "10. Tor et politique fermée", "Service Onion v3 optionnel, persistant et autorisé par appareil. Tor uniquement, direct uniquement, sans relais, sans IP publique et jamais de cloud fournisseur suspendent plutôt que revenir silencieusement. Distribuez l’invitation en privé."),
    ("collaboration", "11. Documents collaboratifs", "Markdown/texte utilise des opérations CRDT bornées et une fusion itérative. L’état reste séparé. ODT/ODS est expérimental; XML dangereux, bombes ZIP, archives et journaux d’opérations excessifs sont refusés avant édition. DOCX/XLSX/PDF reste verrou/version/revue."),
    ("profile", "12. Profil chiffré et migration", "Profil/migration chiffre localement par AES-256-GCM/scrypt et stocke chez le fournisseur OAuth choisi. Identifiants et clés privées sont exclus par défaut. Sur le nouvel appareil, connectez le même fournisseur, inspectez/restaurez, réautorisez puis vérifiez chaque chemin."),
    ("nautilus", "13. Intégration Nautilus", "Nautilus affiche les emblèmes synchronisé, actif, attente, pause, erreur et streaming, plus les actions contextuelles. Depuis 0.19.2, ils sont sans marque et purement fonctionnels : coche verte = synchronisé, flèches circulaires bleues = actif, nuage turquoise avec flèche = streaming, pause violette = pause, losange orange avec horloge = attente, octogone rouge avec point d’exclamation = erreur. Couleur, silhouette et symbole sont tous distincts. Désactivez dans Paramètres en cas de conflit et redémarrez Nautilus."),
    ("updates", "14. Mises à jour sûres", "L’application et un assistant privilégié vérifient indépendamment le manifeste signé. L’assistant copie le paquet dans une zone root privée puis revérifie SHA-256 et identité Debian avant APT; substitution et lien symbolique sont refusés. La version 0.18.1 utilise un pont signé par l’ancienne clé vers 0.19.1; dès 0.19.1, le canal v2 emploie la clé renouvelée. Redémarrez ensuite TuxDrive."),
    ("policies", "15. Réseau, batterie, horaire et débit", "Utilisation maximale n’impose aucune limite. Suspendez sur réseau facturé, batterie faible ou hors plage horaire; limitez le débit par tâche. Les changements différés restent en attente."),
    ("diagnostics", "16. Journaux et diagnostic", "Activité en direct; journaux de tâche sous ~/.cache/tuxdrive/logs; démarrage/application/crash sous ~/.local/state/tuxdrive. Pour signaler: tuxdrive --diagnostics et --system-check --json, reproduire une fois, masquer les secrets. Ne partagez jamais jetons, mots de passe, invitations ou clés privées."),
    ("settings", "17. Paramètres et langue", "Paramètres gère démarrage, notifications, Nautilus, politiques, profil et mises à jour. Le drapeau choisit anglais, allemand, français, espagnol, arabe ou hébreu. Arabe et hébreu s’affichent de droite à gauche sans déplacer les commandes; les diagnostics peuvent rester dans leur langue source."),
    ("uninstall", "18. Désinstallation sûre", "Suspendez et déconnectez les montages. apt remove tuxdrive retire le paquet, pas les contenus ni forcément la configuration. Exportez avant de supprimer configuration, Secret Service ou identités pair; les données chiffrées pourraient devenir inaccessibles."),
))

_ES = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Descripción general", "TuxDrive sincroniza carpetas con ocho proveedores, monta archivos bajo demanda y conecta carpetas cifradas entre pares sin servidor de contenido TuxDrive. Cuentas a la izquierda, trabajos en el centro y actividad abajo.\n\nINICIO\n1. Conecte una cuenta. 2. Añada carpeta o unidad streaming. 3. Revise rutas, dirección y protección. 4. Mantenga una copia independiente antes de la primera sincronización bidireccional."),
    ("accounts", "2. Cuentas y autenticación", "Use + para Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive, Nextcloud o GitHub. OAuth abre la web del proveedor. GitHub usa Git del sistema con agente SSH o gestor de credenciales; se rechazan los tokens incluidos en la URL y TuxDrive no los almacena."),
    ("selective", "3. Selección de carpetas", "El árbol visual carga carpetas al expandir. Marque varias o toda la unidad. Google separa Mi unidad, Compartido conmigo y unidades compartidas. Editar cambia ubicación y ayuda a evitar solapamientos locales peligrosos."),
    ("sync", "4. Modos de sincronización", "Bidireccional propaga creación, cambios, movimientos y borrado. Solo recepción protege cloud; solo envío protege local. Callbacks procesan guardados locales y sondeo detecta remoto. Sincronizar inicia, Detener cancela y el interruptor pausa lo automático."),
    ("streaming", "5. Archivos bajo demanda", "Streaming monta la estructura con FUSE; el contenido baja al abrir. En Nautilus mantenga un elemento o la raíz sin conexión. Las flechas azules indican descarga; solo la marca verde confirma disponibilidad completa. Desconecte antes de borrar el montaje."),
    ("actions", "6. Trabajos y grupos", "Abrir en línea va a la carpeta cloud o rama GitHub. Grupo organiza entradas en grupos internos editables sin mover archivos. GitHub bidireccional confirma, obtiene, rebasa y publica automáticamente; los conflictos detienen la operación. Papelera elimina la definición, no los datos."),
    ("safety", "7. Historial, recuperación y protección", "Historial restaura versiones y reciclaje. Verificar compara; Conflictos exige decisión. Protección masiva/ransomware pausa ráfagas sospechosas. Detenga, revise registro, restaure versión sana, verifique ambos lados y reanude."),
    ("exceptions", "8. Excepciones y conflictos", "Las excepciones son reglas pulsables para temporales/bloqueos o rutas problemáticas verificadas; elimínelas para incluir de nuevo. Google marcado requiere aceptación explícita. Si duda, conserve ambas copias."),
    ("peer", "9. Carpetas privadas entre pares", "Cada dispositivo autorizado obtiene puerto y endpoint SFTP de una sola clave. Lectura/recepción es solo lectura en servidor; envío y entrega única solo ven su buzón privado. Elija dispositivo/rol, guarde/inicie, copie su invitación y verifique la huella. Revoque inmediatamente un dispositivo perdido."),
    ("privacy", "10. Tor y cierre seguro", "Servicio Onion v3 opcional, persistente y con autorización por dispositivo. Solo Tor, solo directo, sin relay, sin IP pública y nunca cloud detienen el tráfico, sin fallback silencioso. Distribuya la invitación en privado."),
    ("collaboration", "11. Documentos colaborativos", "Markdown/texto usa operaciones CRDT limitadas y mezcla iterativa. El estado queda separado. ODT/ODS es experimental; XML inseguro, bombas ZIP y archivos/registros excesivos se rechazan antes de editar. DOCX/XLSX/PDF usa bloqueo/versiones/revisión."),
    ("profile", "12. Perfil cifrado y migración", "Perfil/migración cifra localmente con AES-256-GCM/scrypt y guarda en el proveedor OAuth elegido. Credenciales y claves privadas se excluyen por defecto. En el nuevo equipo conecte el mismo proveedor, inspeccione/restaure, reautorice y verifique rutas."),
    ("nautilus", "13. Integración con Nautilus", "Nautilus muestra emblemas sincronizado, activo, pendiente, pausa, error y streaming, además de acciones. Desde 0.19.2 no llevan marca y son puramente funcionales: marca verde = sincronizado, flechas circulares azules = activo, nube turquesa con flecha = streaming, pausa morada = pausado, rombo naranja con reloj = pendiente y octágono rojo con exclamación = error. Color, silueta y símbolo son distintos. Desactive en Configuración si hay conflicto y reinicie Nautilus."),
    ("updates", "14. Actualizaciones seguras", "La app y un ayudante privilegiado verifican por separado el manifiesto firmado. El ayudante copia a un área privada de root y vuelve a comprobar SHA-256 e identidad Debian antes de APT; rechaza sustituciones y enlaces. La versión 0.18.1 usa un puente firmado con la clave original hacia 0.19.1; desde 0.19.1 el canal v2 usa la clave rotada. Reinicie TuxDrive al terminar."),
    ("policies", "15. Red, batería, horario y ancho de banda", "Uso máximo no restringe. Puede pausar en red medida, batería baja o fuera de horario y limitar ancho de banda por trabajo. Los cambios aplazados no se pierden."),
    ("diagnostics", "16. Registros y diagnóstico", "Actividad en directo; registros de trabajos en ~/.cache/tuxdrive/logs y arranque/app/crash en ~/.local/state/tuxdrive. Para informar ejecute tuxdrive --diagnostics y --system-check --json, reproduzca una vez y oculte secretos. Nunca publique tokens, contraseñas, invitaciones ni claves privadas."),
    ("settings", "17. Configuración e idioma", "Configuración controla inicio, avisos, Nautilus, políticas, perfil y actualizaciones. La bandera selecciona inglés, alemán, francés, español, árabe o hebreo. Árabe y hebreo se muestran de derecha a izquierda sin mover los controles; los diagnósticos pueden conservar su idioma original."),
    ("uninstall", "18. Desinstalación segura", "Pause trabajos y desconecte montajes. apt remove tuxdrive quita el paquete, no los datos ni siempre la configuración. Exporte antes de borrar configuración, Secret Service o identidades; datos cifrados podrían quedar inaccesibles."),
))

_AR = tuple((key, title, body) for (key, title, body) in (
    ("overview", "١. نظرة عامة على TuxDrive", "يزامن TuxDrive المجلدات المختارة مع ثمانية مزودين، ويعرض الملفات عند الطلب، ويربط مجلدات مشفرة بين الأجهزة دون تخزينها على خادم TuxDrive. للبدء: اربط حسابًا، أضف مجلدًا أو محرك بث، راجع المسارات والاتجاه والحماية، واحتفظ بنسخة احتياطية مستقلة قبل أول مزامنة ثنائية الاتجاه."),
    ("accounts", "٢. الحسابات والمصادقة", "استخدم زر الإضافة لربط Google Drive أو OneDrive أو Dropbox أو Box أو pCloud أو MEGA أو Proton Drive أو Nextcloud أو GitHub. يستخدم GitHub برنامج Git في النظام مع وكيل SSH أو مدير بيانات الاعتماد؛ تُرفض الرموز داخل عنوان المستودع ولا يخزنها TuxDrive."),
    ("selective", "٣. اختيار المجلدات والمواقع", "تُحمّل شجرة المجلدات بصريًا عند توسيعها. اختر مجلدًا واحدًا أو أكثر أو المحرك كله. يفصل Google بين ملفاتي والمشترك معي والمحركات المشتركة. لتغيير الاختيار افتح تحرير، راجع الموقع والمسارات المحلية وتجنب التداخل غير الآمن ثم احفظ."),
    ("sync", "٤. أوضاع المزامنة والاستدعاءات", "تنقل المزامنة الثنائية الإنشاء والتعديل والنقل والحذف في الاتجاهين. يحمي وضع التنزيل فقط السحابة ويحمي الرفع فقط الجانب المحلي. استخدم مزامنة الآن للتشغيل وإيقاف للإلغاء والمفتاح الصغير لتعليق العمل التلقائي، وافحص السجل قبل أي استرداد قسري."),
    ("streaming", "٥. الملفات عند الطلب والعمل دون اتصال", "يركب وضع البث بنية السحابة بواسطة FUSE وتُنزل المحتويات عند فتح الملف. من Nautilus يمكن الاحتفاظ بعنصر أو جذر المحرك دون اتصال. تشير الأسهم الزرقاء إلى التنزيل ولا تؤكد علامة الصح الخضراء إلا اكتمال التخزين المحلي."),
    ("actions", "٦. المهام والمجموعات", "يفتح فتح عبر الإنترنت مجلد السحابة أو فرع GitHub. تنظم المجموعة العناصر في مجموعات داخلية قابلة لإعادة التسمية دون نقل الملفات. تنفذ مزامنة GitHub الثنائية commit وfetch وrebase وpush تلقائيًا وتتوقف بأمان عند التعارض. تحذف سلة المهملات التعريف لا البيانات."),
    ("safety", "٧. الاسترداد والإصدارات والحماية", "يعيد السجل الإصدارات والملفات المحذوفة محليًا، ويقارن التحقق الجانبين، ويعرض مركز التعارضات القرارات المطلوبة. توقف حماية التغيير الجماعي وبرامج الفدية العمليات المشبوهة. عند مشكلة أوقف المهمة، راجع السجل، استعد نسخة سليمة، تحقق من الجانبين ثم استأنف."),
    ("exceptions", "٨. الاستثناءات والتعارضات", "الاستثناءات قواعد قابلة للنقر للملفات المؤقتة أو المقفلة والمسارات التي راجعتها. احذف القاعدة لإعادة تضمين المسار. يتطلب ملف Google المصنف خطرًا موافقة صريحة. عند الشك اختر الاحتفاظ بالنسختين بدل استبدال إحداهما تلقائيًا."),
    ("peer", "٩. المجلدات الخاصة بين الأجهزة", "يحصل كل جهاز مصرح له على منفذ ونقطة SFTP بمفتاح واحد. يفرض الخادم القراءة فقط، بينما يرى الإرسال فقط والإيداع لمرة واحدة صندوقهما الخاص دون مساحة العمل. اختر الجهاز والدور، احفظ وشغّل، وانسخ دعوته وتحقق من البصمة. ألغِ الجهاز المفقود فورًا."),
    ("privacy", "١٠. Tor وسياسات الإغلاق الآمن", "يمكن نشر مساحة العمل كخدمة Onion v3 مع تفويض عميل لكل جهاز. تشمل السياسات Tor فقط أو مباشر فقط أو دون ترحيل أو دون اكتشاف IP عام أو دون سحابة. أي مخالفة توقف النقل ولا تستخدم اتصالًا بديلًا بصمت. وزع الدعوة وبيانات التفويض بصورة خاصة."),
    ("collaboration", "١١. المستندات التعاونية", "تستخدم ملفات Markdown والنص عمليات CRDT محدودة ودمجًا تكراريًا. يبقى الوضع منفصلًا. دعم ODT وODS تجريبي؛ يُرفض XML غير الآمن وقنابل ZIP والأرشيف أو سجل العمليات المفرط قبل التحرير. تستخدم DOCX وXLSX وPDF القفل والإصدارات."),
    ("profile", "١٢. النسخ الاحتياطي المشفر والترحيل", "تشفّر أداة الملف الشخصي الإعدادات محليًا بواسطة AES-256-GCM وscrypt وتحفظها لدى مزود OAuth مختار. تُستبعد بيانات الاعتماد والمفاتيح الخاصة افتراضيًا. على الجهاز الجديد اربط المزود نفسه، افحص النسخة، استعدها، أعد تفويض الحسابات وتحقق من كل مسار قبل التفعيل."),
    ("nautilus", "١٣. تكامل Nautilus", "يعرض Nautilus شارات متزامن وقيد المزامنة ومعلق ومتوقف وخطأ وبث، إضافة إلى إجراءات السياق للمزامنة وفتح السحابة والسجل والتوفر دون اتصال. منذ الإصدار 0.19.2 أصبحت الشارات بلا علامة تجارية ووظيفية فقط: علامة صح خضراء للمتزامن، سهمان دائريان أزرقان للمزامنة، سحابة فيروزية مع سهم للبث، إيقاف مؤقت بنفسجي، معين برتقالي مع ساعة للمعلق، وثماني أحمر مع علامة تعجب للخطأ. يختلف اللون والشكل والرمز لكل حالة. إذا تعارض الامتداد مع إضافة أخرى عطله من الإعدادات ثم أعد تشغيل Nautilus."),
    ("updates", "١٤. التحديثات الآمنة", "يتحقق التطبيق ومساعد مميز بصورة مستقلة من البيان الموقع. ينسخ المساعد الحزمة إلى منطقة خاصة بالجذر ثم يعيد فحص SHA-256 وهوية Debian قبل APT ويرفض الاستبدال والروابط الرمزية. يستخدم الإصدار 0.18.1 جسراً موقعاً بالمفتاح الأصلي إلى 0.19.1، ومن 0.19.1 تستخدم قناة v2 المفتاح الجديد. أعد تشغيل TuxDrive بعد النجاح."),
    ("policies", "١٥. الشبكة والبطارية والجدول", "لا يفرض وضع الاستخدام الأقصى أي قيود افتراضيًا. يمكن تعليق النقل على شبكة محسوبة أو عند انخفاض البطارية أو خارج الجدول اليومي، كما يمكن تحديد السرعة لكل مهمة. تؤجل هذه السياسات العمل ولا تحذف التغييرات المنتظرة."),
    ("diagnostics", "١٦. السجلات والتشخيص", "يعرض السجل المباشر نشاط التطبيق وتوجد سجلات المهام في ~/.cache/tuxdrive/logs وسجلات البدء والتعطل في ~/.local/state/tuxdrive. للإبلاغ شغّل tuxdrive --diagnostics وtuxdrive --system-check --json وأخفِ الأسرار. لا تنشر الرموز أو كلمات المرور أو الدعوات أو المفاتيح الخاصة."),
    ("settings", "١٧. الإعدادات واللغة", "تتحكم الإعدادات في بدء الدخول والإشعارات وNautilus وسياسات النقل والملف الشخصي والتحديثات. يبدل العلم في الشريط العلوي الإنجليزية والألمانية والفرنسية والإسبانية والعربية والعبرية ويحفظ الاختيار. يظهر النص العربي والعبراني من اليمين إلى اليسار دون تغيير ترتيب الواجهة."),
    ("uninstall", "١٨. إزالة TuxDrive بأمان", "أوقف المهام وافصل محركات البث قبل الإزالة. يحذف apt remove tuxdrive الحزمة ولا يحذف بالضرورة البيانات أو الإعدادات. صدّر نسخة قبل حذف الإعداد أو Secret Service أو هويات الأجهزة، لأن فقد كلمة مرور أو مفتاح قد يجعل البيانات المشفرة غير قابلة للاسترداد."),
))

_HE = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. סקירה כללית של TuxDrive", "TuxDrive מסנכרן תיקיות נבחרות עם שמונה ספקים, מציג קבצים לפי דרישה ומחבר תיקיות עמיתים מוצפנות בלי לאחסן אותן בשרת TuxDrive. להתחלה: חברו חשבון, הוסיפו תיקייה או כונן הזרמה, בדקו נתיבים, כיוון והגנות ושמרו גיבוי עצמאי לפני הסנכרון הדו־כיווני הראשון."),
    ("accounts", "2. חשבונות ואימות", "השתמשו בכפתור ההוספה עבור Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive, Nextcloud או GitHub. GitHub משתמש ב-Git של המערכת עם סוכן SSH או מנהל אישורים; אסימונים בתוך כתובת המאגר נדחים ואינם נשמרים ב-TuxDrive."),
    ("selective", "3. בחירת תיקיות ומיקומי ענן", "עץ התיקיות נטען כאשר מרחיבים ענפים. אפשר לבחור תיקייה אחת, כמה תיקיות או את כל הכונן. Google מפריד בין הכונן שלי, משותף איתי וכוננים משותפים. לשינוי הבחירה פתחו עריכה, בדקו את המיקום והיעדים המקומיים, מנעו חפיפה מסוכנת ושמרו."),
    ("sync", "4. מצבי סנכרון וקריאות שינוי", "סנכרון דו־כיווני מעביר יצירה, שינוי, העברה ומחיקה בשני הכיוונים. קבלה בלבד מגנה על הענן ושליחה בלבד מגנה על הצד המקומי. סנכרון עכשיו מפעיל, עצירה מבטלת והמתג משהה עבודה אוטומטית. בדקו מצב ויומן לפני שחזור כפוי."),
    ("streaming", "5. קבצים לפי דרישה וזמינות לא מקוונת", "כונן הזרמה מעגן את הענן באמצעות FUSE ומוריד תוכן בפתיחה. ב-Nautilus אפשר לשמור פריט או את שורש הכונן לא מקוון. חצים כחולים מציינים הורדה ורק הסימון הירוק מאשר זמינות מלאה ללא רשת."),
    ("actions", "6. משימות וקבוצות", "פתיחה בענן מציגה תיקיית ענן או ענף GitHub. קבוצה מסדרת רשומות בקבוצות פנימיות הניתנות לשינוי שם בלי להזיז קבצים. סנכרון GitHub דו־כיווני מבצע commit, fetch, rebase ו-push אוטומטית ועוצר בבטחה בהתנגשות. סל המחזור מסיר הגדרה ולא נתונים."),
    ("safety", "7. שחזור, גרסאות והגנה", "היסטוריה משחזרת גרסאות ומחיקות מקומיות, אימות משווה בין הצדדים ומרכז התנגשויות דורש החלטה מפורשת. הגנת שינוי המוני וכופרה משהה פעילות חשודה. במקרה בעיה עצרו, בדקו יומן, שחזרו גרסה תקינה, אמתו את שני הצדדים ורק אז המשיכו."),
    ("exceptions", "8. חריגים והתנגשויות", "חריגי סנכרון הם כללים לחיצים עבור קבצים זמניים, קבצי נעילה או נתיב בעייתי שנבדק. הסירו כלל כדי לכלול את הנתיב שוב. קובץ Google שסומן כמסוכן דורש אישור מפורש. אם אינכם בטוחים בחרו לשמור את שני העותקים."),
    ("peer", "9. תיקיות עמיתים פרטיות", "כל התקן מורשה מקבל יציאת SFTP ונקודת קצה עם מפתח יחיד. קריאה/קבלה נאכפת כקריאה בלבד בשרת; שליחה וטיפה חד־פעמית רואות רק תיבת דואר פרטית. בחרו התקן ותפקיד, שמרו והפעילו, העתיקו את הזמנתו ואמתו טביעה. בטלו מיד התקן שאבד."),
    ("privacy", "10. Tor ומדיניות כשל סגור", "מרחב עבודה יכול לפרסם שירות Onion v3 עם הרשאת לקוח נפרדת לכל התקן. המדיניות כוללת Tor בלבד, ישיר בלבד, ללא ממסר, ללא גילוי IP ציבורי ולעולם ללא ענן ספק. הפרה משהה תעבורה בלי נסיגה שקטה לחיבור אחר. העבירו הזמנות והרשאות באופן פרטי."),
    ("collaboration", "11. מסמכים שיתופיים", "Markdown וטקסט משתמשים בפעולות CRDT מוגבלות ובמיזוג איטרטיבי. המצב נשמר בנפרד. ODT ו-ODS ניסיוניים; XML מסוכן, פצצות ZIP וארכיונים או יומני פעולות מופרזים נדחים לפני עריכה. DOCX, XLSX ו-PDF משתמשים בנעילות וגרסאות."),
    ("profile", "12. גיבוי מוצפן והעברת התקן", "כלי הפרופיל מצפין הגדרות מקומית באמצעות AES-256-GCM ו-scrypt ושומר אצל ספק OAuth שנבחר. הרשאות ומפתחות פרטיים אינם נכללים כברירת מחדל. בהתקן החדש חברו אותו ספק, בדקו ושחזרו את הגיבוי, אשרו מחדש חשבונות ובדקו כל נתיב לפני הפעלה."),
    ("nautilus", "13. שילוב Nautilus", "Nautilus מציג סמלים עבור מסונכרן, פעיל, ממתין, מושהה, שגיאה והזרמה, ופעולות לסנכרון, פתיחה בענן, יומן וזמינות לא מקוונת. מגרסה 0.19.2 הסמלים נטולי מיתוג ותפקודיים בלבד: סימן וי ירוק = מסונכרן, חצים מעגליים כחולים = מסנכרן, ענן טורקיז עם חץ = הזרמה, השהיה סגולה = מושהה, מעוין כתום עם שעון = ממתין ומתומן אדום עם סימן קריאה = שגיאה. הצבע, הצורה והסמל שונים בכל מצב. אם יש התנגשות עם הרחבה אחרת השביתו את השילוב בהגדרות והפעילו מחדש את Nautilus."),
    ("updates", "14. עדכונים מאובטחים", "האפליקציה ומסייע מורשה מאמתים בנפרד את המניפסט החתום. המסייע מעתיק לאזור פרטי של root ובודק שוב SHA-256 וזהות Debian לפני APT; החלפה וקישור סמלי נדחים. גרסה 0.18.1 משתמשת בגשר החתום במפתח המקורי אל 0.19.1; מגרסה 0.19.1 ערוץ v2 משתמש במפתח החדש. הפעילו מחדש את TuxDrive לאחר הצלחה."),
    ("policies", "15. רשת, סוללה, לוח זמנים ורוחב פס", "ברירת המחדל שימוש מרבי אינה מגבילה העברות. אפשר להשהות ברשת מדודה, מתחת לסף סוללה או מחוץ לשעות יומיות ולהגביל רוחב פס לכל משימה. המדיניות דוחה עבודה ואינה מוחקת שינויים ממתינים."),
    ("diagnostics", "16. יומנים ואבחון", "יומן הפעילות מציג עבודה שוטפת; יומני משימה נמצאים ב-~/.cache/tuxdrive/logs ויומני התחלה וקריסה ב-~/.local/state/tuxdrive. לדיווח הריצו tuxdrive --diagnostics ו-tuxdrive --system-check --json והסתירו סודות. אל תפרסמו אסימונים, סיסמאות, הזמנות או מפתחות פרטיים."),
    ("settings", "17. הגדרות ושפה", "ההגדרות שולטות בהפעלה, התראות, Nautilus, מדיניות העברה, פרופיל ועדכונים. הדגל בסרגל העליון מחליף ושומר אנגלית, גרמנית, צרפתית, ספרדית, ערבית או עברית. טקסט עברי וערבי מוצג מימין לשמאל בלי לשנות את מבנה החלון."),
    ("uninstall", "18. הסרה בטוחה של TuxDrive", "השהו משימות ונתקו עיגוני הזרמה לפני הסרה. apt remove tuxdrive מסיר את החבילה אך לא בהכרח נתונים או הגדרות. ייצאו גיבוי לפני מחיקת תצורה, Secret Service או זהויות עמיתים; אובדן סיסמה או מפתח עלול להפוך מידע מוצפן לבלתי ניתן לשחזור."),
))

_TOPICS = {"en": _EN, "de": _DE, "fr": _FR, "es": _ES, "ar": _AR, "he": _HE}


def topics(language: str) -> tuple[HelpTopic, ...]:
    selected = _TOPICS.get(language, _EN)
    return tuple(HelpTopic(*item) for item in selected)
