"""Localized, offline user documentation displayed by the desktop client."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HelpTopic:
    key: str
    title: str
    body: str


_EN = (
    ("overview", "1. TuxDrive overview", "TuxDrive synchronizes selected folders with eight cloud providers, mounts files on demand, and connects encrypted peer folders without storing peer data on a TuxDrive server. The left side lists accounts; the center lists jobs; the bottom log explains current activity. Provider icons identify the storage service and state text/badges show connected, syncing, paused, or error conditions.\n\nHOW TO START\n1. Connect an account. 2. Add a synchronized folder or streaming drive. 3. Review the cloud path, local path, direction and safety settings. 4. Keep an independent backup before the first two-way synchronization."),
    ("accounts", "2. Cloud accounts and authentication", "Use + or Connect account for Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive, or Nextcloud. Browser-OAuth providers open their own login page; TuxDrive never receives that password. Proton/MEGA/Nextcloud use guided credentials and Proton can request a separate 2FA code. Credentials are stored through encrypted rclone configuration protected by Secret Service.\n\nHOW TO REPAIR AUTHORIZATION\nOpen the account menu → Reconnect / refresh credentials. Complete authorization and wait for cloud verification. Remove an account only after deleting jobs that use it."),
    ("selective", "3. Folder selection and cloud locations", "The visual tree loads folders lazily. Check one or more folders, expand arrows to browse deeper, or select the entire drive. Google Drive exposes My Drive, Shared with me, and each Shared Drive as separate locations. One selected cloud folder creates one job and local destination.\n\nHOW TO CHANGE SELECTION\nChoose Edit on a job, select the intended drive/location and tree nodes, verify that local destinations do not overlap unsafely, then save."),
    ("sync", "4. Synchronization modes and callbacks", "Two-way sync propagates creations, modifications, moves and deletions in both directions. Download-only/receive-only protects the cloud side; upload-only/send-only protects the local side. Real-time callbacks detect saved local changes and transfer changed paths; polling detects remote changes. Block-delta transfer is used for supported direct peers.\n\nHOW TO RUN OR PAUSE\nSync now starts a run. Stop cancels the active process. The compact switch enables or pauses automatic work. Check the status and View log before forcing recovery after an error."),
    ("streaming", "5. Files on demand and offline availability", "A streaming drive mounts the cloud hierarchy with FUSE. Folder names appear immediately while file bodies download when opened. The mount point must be empty. A streaming child can live inside a normal synchronized tree because TuxDrive excludes that subtree; a streaming parent of another sync is unsafe.\n\nHOW TO USE\nAdd folder → Streaming drive, choose the cloud subtree and empty mount folder, then Start streaming. In Nautilus right-click a streamed item to keep it offline or return it to online-only. Disconnect cleanly before deleting a mount point."),
    ("actions", "6. Job buttons and online folders", "Open folder opens the local destination. Open online opens the exact provider folder when supported. Share link requests a provider link and copies it. Rename changes only the label inside TuxDrive. Edit changes paths, mode, interval, filters and protection. View log opens transfer logs. The trash button removes the job definition but does not delete local or cloud data."),
    ("safety", "7. Recovery, versions, integrity and ransomware protection", "History restores locally retained versions and recycled deletions. Verify compares local/cloud content and offers selected repairs. Conflicts opens mismatches for explicit review. Mass-change/ransomware protection pauses suspicious deletion or extension bursts before propagation; it is a safety boundary, not antivirus. Maximum deletions limits destructive runs.\n\nHOW TO RECOVER\nStop the job, inspect View log and Conflicts, restore a known-good version, verify both sides, then resume. Never approve a mass-change event until the source device is clean."),
    ("exceptions", "8. Exceptions, conflicts and unsafe provider files", "Synchronization exceptions are clickable rules. Add temporary/lock files or a failing path after reviewing the error; remove a rule to include it again. Google files flagged as malware/spam require an explicit unsafe-download acknowledgement. Conflict policy can keep both copies, prefer local, or prefer cloud; keeping both is safest when uncertain."),
    ("peer", "9. Private peer-to-peer folders", "Peer sharing uses authenticated, host-key-pinned SFTP and individual device identity keys. A host selects a folder, address/port and authorized devices; guests import a signed invitation/QR and select a local folder. Roles are read/write, read-only, send-only or receive-only. LAN discovery finds candidates but users must verify fingerprints. Optional NAT mapping or ciphertext-only relay can help reachability.\n\nHOW TO PAIR\nExchange public keys through a trusted channel, authorize the named device, copy the invitation, verify the host fingerprint on the guest, then connect. Revoke a lost device and restart the share."),
    ("privacy", "10. Tor and fail-closed privacy", "A peer workspace can publish a Tor v3 Onion Service, optionally persistent and protected with per-device client authorization. Policies include Tor only, direct only, no relay, no public-IP discovery, and never use provider cloud. Violations pause traffic instead of falling back silently. Bridges/pluggable transports are advanced settings and secrets are excluded from invitations/logs.\n\nHOW TO USE TOR ONLY\nInstall Tor, choose Tor only, enable Onion Service and optionally client authorization, save/start, then distribute the private invitation securely. Confirm that no direct/relay endpoint appears."),
    ("collaboration", "11. Collaborative documents", "Markdown/text uses an operation CRDT: peers edit offline, immutable operations synchronize, and deterministic merge produces the same text. Collaboration state stays in .tuxdrive-collaboration; Export checkpoint writes an ordinary file. Optional encrypted presence shows cursors/selections briefly without permanent audit storage. Comments, suggestions, tracked changes, approvals and tasks are review events.\n\nODT/ODS support is experimental structured import/export with deterministic snapshots and original XML recovery. DOCX/XLSX/PDF remain under leases, versions and review, not real-time editing."),
    ("profile", "12. Encrypted profile backup and migration", "Settings → TuxDrive Profile / migrate encrypts configuration locally with AES-256-GCM/scrypt and stores it in a selected OAuth provider. By default OAuth credentials and peer private keys are excluded. Sensitive inclusion is explicit and requires the same strong password during restore. TuxDrive cannot recover that password.\n\nHOW TO MIGRATE\nBack up on the old device, install TuxDrive on the new device, connect the same provider, inspect the discovered backup, restore, then reauthorize excluded accounts and verify every path before enabling jobs."),
    ("nautilus", "13. Nautilus integration", "When enabled, Nautilus displays synchronized/syncing/pending/paused/error/streaming emblems and context actions for sync, online folder, logs and offline availability. The extension reads a private state file and sends actions to the running application. Disable it in Settings if another extension conflicts, then restart Nautilus."),
    ("updates", "14. Secure in-app updates", "Settings → Check for updates downloads a signed expiring manifest. TuxDrive verifies Ed25519 signature, approved repository URL, SHA-256, package identity/version and size before PolicyKit asks for administrator authorization. A failed verification leaves the current installation unchanged.\n\nHOW TO UPDATE\nCheck, review version/notes, Download and install, approve the system prompt, then restart TuxDrive. If it claims an old version is current, wait briefly for repository cache refresh and retry."),
    ("policies", "15. Network, battery, schedule and bandwidth", "Default Maximum usage applies no transfer restriction. Settings can pause on metered networks, below a battery threshold, or outside a daily schedule. Per-job bandwidth limits constrain rclone traffic. Policies defer work; they do not discard queued changes."),
    ("diagnostics", "16. Logs, health dashboard and diagnostics", "The live log shows application activity. View log opens job-specific rclone logs. The health dashboard combines job state, callbacks/mounts, peer audit events and provider capabilities. Startup/application/crash logs are under ~/.local/state/tuxdrive; transfer logs are under ~/.cache/tuxdrive/logs.\n\nHOW TO REPORT A PROBLEM\nRun tuxdrive --diagnostics and tuxdrive --system-check --json, reproduce once, then attach relevant redacted logs. Never publish OAuth tokens, passwords, invitations, private keys, Onion authorization or bridge secrets."),
    ("settings", "17. Settings and language", "Settings controls login startup, notifications, minimized startup, Nautilus integration, transfer policies, profile migration and updates. The flag in the top bar changes English, German, French or Spanish immediately and stores the choice for the next start. Language changes labels and the documentation center; provider/rclone diagnostic text may remain in its source language."),
    ("uninstall", "18. Removing TuxDrive safely", "Pause jobs and disconnect streaming mounts before uninstalling. Removing a job/account does not delete synchronized content. Uninstall the package with apt remove tuxdrive. Configuration and encrypted credentials remain for reinstall unless deliberately removed. Before deleting ~/.config/tuxdrive, rclone configuration, Secret Service entries or peer identities, export what is needed and understand that encrypted remotes may become inaccessible."),
)

# The translated editions intentionally mirror every English topic and numbered
# procedure. Provider-generated error text can still be English.
_DE = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Überblick", "TuxDrive synchronisiert ausgewählte Ordner mit acht Cloud-Anbietern, stellt Dateien bei Bedarf bereit und verbindet verschlüsselte Peer-Ordner ohne TuxDrive-Inhaltsserver. Links stehen Konten, in der Mitte Aufträge und unten das Aktivitätsprotokoll.\n\nSCHNELLSTART\n1. Konto verbinden. 2. Synchronisierten Ordner oder Streaming-Laufwerk hinzufügen. 3. Cloud-/lokalen Pfad, Richtung und Schutz prüfen. 4. Vor der ersten Zwei-Wege-Synchronisierung unabhängig sichern."),
    ("accounts", "2. Cloud-Konten und Anmeldung", "Über + oder Konto verbinden: Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive oder Nextcloud. OAuth öffnet die Anbieter-Webseite; TuxDrive erhält das Passwort nicht. Proton kann einen separaten 2FA-Code verlangen. Zugangsdaten liegen in der verschlüsselten rclone-Konfiguration mit Secret Service.\n\nREPARATUR\nKontomenü → Anmeldedaten erneuern, Autorisierung abschließen und Cloud-Prüfung abwarten."),
    ("selective", "3. Ordnerauswahl und Cloud-Bereiche", "Der visuelle Baum lädt Ordner bei Bedarf. Mehrere Ordner oder das ganze Laufwerk können markiert werden. Google trennt Meine Ablage, Für mich freigegeben und geteilte Ablagen. Über Bearbeiten Auswahl/Pfade ändern und gefährliche Überschneidungen vermeiden."),
    ("sync", "4. Synchronisierungsarten und Rückrufe", "Zwei Wege überträgt Erstellen, Ändern, Verschieben und Löschen in beide Richtungen. Nur Download/Empfangen schützt die Cloud; nur Upload/Senden schützt lokal. Rückrufe übertragen gespeicherte lokale Änderungen, Polling erkennt Remote-Änderungen. Jetzt synchronisieren startet, Stoppen bricht ab, der Schalter pausiert Automatik."),
    ("streaming", "5. Dateien bei Bedarf und Offline-Nutzung", "Streaming bindet die Cloud-Struktur über FUSE ein; Dateiinhalte kommen erst beim Öffnen. Der Einhängeordner muss leer sein. In Nautilus kann ein Element offline behalten oder wieder nur online gesetzt werden. Vor dem Löschen des Ordners sauber trennen."),
    ("actions", "6. Auftragsaktionen", "Ordner öffnen öffnet lokal; Online öffnen den genauen Cloud-Ordner; Link teilen kopiert einen Anbieterlink. Umbenennen ändert nur die Anzeige. Bearbeiten ändert Pfade/Modus/Filter. Protokoll zeigt Details. Papierkorb entfernt nur die Definition, keine Daten."),
    ("safety", "7. Verlauf, Wiederherstellung und Schutz", "Verlauf stellt lokale Versionen/Papierkorb wieder her. Prüfen vergleicht beide Seiten; Konflikte verlangt eine Entscheidung. Massenänderungs-/Ransomware-Schutz pausiert verdächtige Löschungen oder Endungen. Auftrag stoppen, Protokoll prüfen, gute Version wiederherstellen, beide Seiten verifizieren, dann fortsetzen."),
    ("exceptions", "8. Ausnahmen und Konflikte", "Ausnahmen sind anklickbare Regeln für temporäre/Sperrdateien oder geprüfte Fehlerpfade und können wieder entfernt werden. Unsichere Google-Downloads brauchen ausdrückliche Zustimmung. Bei Unsicherheit Konfliktregel Beide behalten verwenden."),
    ("peer", "9. Private Peer-Ordner", "Peer-Freigabe nutzt authentifiziertes, hostschlüsselgebundenes SFTP und einzelne Geräteschlüssel. Host wählt Ordner/Adresse/Port/autorisierte Geräte; Gast importiert Einladung/QR und prüft Fingerabdruck. Rollen: Lesen/Schreiben, nur Lesen, nur Senden, nur Empfangen. Verlorenes Gerät widerrufen und Freigabe neu starten."),
    ("privacy", "10. Tor und Fail-closed", "Optionaler Tor-v3-Onion-Service mit dauerhafter Identität und Geräteautorisierung. Richtlinien Tor-only, Direct-only, kein Relay, keine öffentliche IP und keine Provider-Cloud pausieren bei Verstoß statt still zurückzufallen. Einladung privat verteilen und prüfen, dass keine verbotenen Endpunkte enthalten sind."),
    ("collaboration", "11. Gemeinsame Dokumente", "Markdown/Text verwendet CRDT-Operationen für Offline-Bearbeitung und deterministische Zusammenführung. Zustand liegt separat in .tuxdrive-collaboration; Export erzeugt eine normale Datei. Verschlüsselte kurzlebige Präsenz, Kommentare, Vorschläge, Freigaben und Aufgaben sind möglich. ODT/ODS ist experimentell; DOCX/XLSX/PDF bleibt Sperre/Version/Review."),
    ("profile", "12. Verschlüsseltes Profil und Umzug", "Profil/Migration verschlüsselt Konfiguration lokal per AES-256-GCM/scrypt und speichert sie beim gewählten OAuth-Anbieter. Zugangsdaten/private Peer-Schlüssel sind standardmäßig ausgeschlossen. Auf neuem Gerät gleichen Anbieter verbinden, Backup prüfen/wiederherstellen, Konten neu autorisieren und Pfade prüfen."),
    ("nautilus", "13. Nautilus-Integration", "Nautilus zeigt Embleme für synchronisiert, aktiv, ausstehend, pausiert, Fehler und Streaming sowie Kontextaktionen. Bei Konflikten in Einstellungen deaktivieren und Nautilus neu starten."),
    ("updates", "14. Sichere Updates", "Update prüft signiertes, ablaufendes Manifest, Ed25519, URL, SHA-256, Paketname/-version und Größe vor PolicyKit. Prüfung starten, Hinweise lesen, herunterladen/installieren, Systemabfrage bestätigen und TuxDrive neu starten. Fehler verändert die Installation nicht."),
    ("policies", "15. Netzwerk, Akku, Zeit und Bandbreite", "Maximale Nutzung ist uneingeschränkt. Optional bei getaktetem Netz, niedrigem Akku oder außerhalb des Zeitfensters pausieren. Bandbreite pro Auftrag begrenzen. Aufgeschobene Änderungen gehen nicht verloren."),
    ("diagnostics", "16. Protokolle und Diagnose", "Live-Protokoll zeigt Aktivität; Auftragsprotokolle liegen unter ~/.cache/tuxdrive/logs, Start/App/Crash unter ~/.local/state/tuxdrive. Problem melden: tuxdrive --diagnostics und --system-check --json ausführen, einmal reproduzieren, Logs schwärzen. Niemals Token, Passwörter, private Schlüssel oder Onion-/Bridge-Geheimnisse senden."),
    ("settings", "17. Einstellungen und Sprache", "Einstellungen: Autostart, Benachrichtigungen, minimierter Start, Nautilus, Übertragungsrichtlinien, Profil und Updates. Die Flagge oben wechselt Englisch, Deutsch, Französisch oder Spanisch sofort und dauerhaft. Anbieter-/rclone-Fehler können in der Ursprungssprache bleiben."),
    ("uninstall", "18. Sicher entfernen", "Aufträge pausieren und Streaming trennen. apt remove tuxdrive entfernt das Paket, nicht automatisch Inhalte/Konfiguration. Vor dem Löschen von Konfiguration, Secret-Service-Einträgen oder Peer-Identitäten exportieren; sonst können verschlüsselte Daten unzugänglich werden."),
))

_FR = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Présentation", "TuxDrive synchronise des dossiers avec huit fournisseurs, monte les fichiers à la demande et relie des dossiers pair-à-pair chiffrés sans serveur de contenu TuxDrive. Comptes à gauche, tâches au centre, activité en bas.\n\nDÉMARRAGE\n1. Connectez un compte. 2. Ajoutez un dossier ou lecteur streaming. 3. Vérifiez chemins, sens et protections. 4. Gardez une sauvegarde indépendante avant la première synchronisation bidirectionnelle."),
    ("accounts", "2. Comptes et authentification", "Utilisez + pour Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive ou Nextcloud. OAuth ouvre le site du fournisseur; TuxDrive ne reçoit pas le mot de passe. Proton peut demander un code 2FA séparé. Les secrets sont dans la configuration rclone chiffrée protégée par Secret Service. Réparer via menu du compte → Actualiser les identifiants."),
    ("selective", "3. Sélection des dossiers", "L’arbre visuel charge les dossiers à la demande. Cochez plusieurs dossiers ou tout le lecteur. Google sépare Mon Drive, Partagés avec moi et les Drives partagés. Modifier permet de changer l’emplacement et d’éviter les chevauchements locaux dangereux."),
    ("sync", "4. Modes de synchronisation", "Bidirectionnel propage créations, modifications, déplacements et suppressions. Réception seule protège le cloud; envoi seul protège le local. Les rappels traitent les sauvegardes locales, le sondage détecte le distant. Synchroniser lance, Arrêter annule, l’interrupteur suspend l’automatique."),
    ("streaming", "5. Fichiers à la demande", "Le streaming monte l’arborescence avec FUSE; le contenu arrive à l’ouverture. Le point de montage doit être vide. Dans Nautilus, conservez un élément hors ligne ou remettez-le en ligne uniquement. Déconnectez avant de supprimer le montage."),
    ("actions", "6. Actions d’une tâche", "Ouvrir dossier ouvre le local; Ouvrir en ligne cible le dossier cloud; Lien de partage copie un lien. Renommer change seulement l’étiquette. Modifier change chemins/mode/filtres. Journal affiche les détails. La corbeille retire la définition sans supprimer les données."),
    ("safety", "7. Historique, récupération et protection", "Historique restaure versions et suppressions recyclées. Vérifier compare les côtés; Conflits exige une décision. La protection contre changements massifs/ransomware suspend les rafales suspectes. Arrêtez, lisez le journal, restaurez une version saine, vérifiez puis reprenez."),
    ("exceptions", "8. Exceptions et conflits", "Les exceptions sont des règles cliquables pour fichiers temporaires/verrouillés ou chemins problématiques vérifiés. Supprimez la règle pour réinclure. Les téléchargements Google signalés exigent un accord explicite. En cas de doute, conservez les deux copies."),
    ("peer", "9. Dossiers pair-à-pair privés", "Partage via SFTP authentifié avec clé d’hôte épinglée et clés par appareil. L’hôte choisit dossier/adresse/port/appareils; l’invité importe invitation/QR et vérifie l’empreinte. Rôles lecture-écriture, lecture, envoi ou réception. Révoquez immédiatement un appareil perdu."),
    ("privacy", "10. Tor et politique fermée", "Service Onion v3 optionnel, persistant et autorisé par appareil. Tor uniquement, direct uniquement, sans relais, sans IP publique et jamais de cloud fournisseur suspendent plutôt que revenir silencieusement. Distribuez l’invitation en privé."),
    ("collaboration", "11. Documents collaboratifs", "Markdown/texte utilise un CRDT pour édition hors ligne et convergence déterministe. L’état reste dans .tuxdrive-collaboration; Export produit un fichier normal. Présence chiffrée éphémère, commentaires, suggestions, validations et tâches. ODT/ODS expérimental; DOCX/XLSX/PDF reste verrou/version/revue."),
    ("profile", "12. Profil chiffré et migration", "Profil/migration chiffre localement par AES-256-GCM/scrypt et stocke chez le fournisseur OAuth choisi. Identifiants et clés privées sont exclus par défaut. Sur le nouvel appareil, connectez le même fournisseur, inspectez/restaurez, réautorisez puis vérifiez chaque chemin."),
    ("nautilus", "13. Intégration Nautilus", "Nautilus affiche les emblèmes synchronisé, actif, attente, pause, erreur et streaming, plus les actions contextuelles. Désactivez dans Paramètres en cas de conflit et redémarrez Nautilus."),
    ("updates", "14. Mises à jour sûres", "Le contrôle vérifie manifeste signé/expirant, Ed25519, URL, SHA-256, identité/version du paquet et taille avant PolicyKit. Vérifiez, lisez les notes, téléchargez/installez, autorisez puis redémarrez. Un échec laisse la version actuelle intacte."),
    ("policies", "15. Réseau, batterie, horaire et débit", "Utilisation maximale n’impose aucune limite. Suspendez sur réseau facturé, batterie faible ou hors plage horaire; limitez le débit par tâche. Les changements différés restent en attente."),
    ("diagnostics", "16. Journaux et diagnostic", "Activité en direct; journaux de tâche sous ~/.cache/tuxdrive/logs; démarrage/application/crash sous ~/.local/state/tuxdrive. Pour signaler: tuxdrive --diagnostics et --system-check --json, reproduire une fois, masquer les secrets. Ne partagez jamais jetons, mots de passe, invitations ou clés privées."),
    ("settings", "17. Paramètres et langue", "Paramètres gère démarrage, notifications, Nautilus, politiques, profil et mises à jour. Le drapeau supérieur bascule immédiatement et durablement anglais, allemand, français ou espagnol. Les erreurs du fournisseur/rclone peuvent rester dans leur langue source."),
    ("uninstall", "18. Désinstallation sûre", "Suspendez et déconnectez les montages. apt remove tuxdrive retire le paquet, pas les contenus ni forcément la configuration. Exportez avant de supprimer configuration, Secret Service ou identités pair; les données chiffrées pourraient devenir inaccessibles."),
))

_ES = tuple((key, title, body) for (key, title, body) in (
    ("overview", "1. Descripción general", "TuxDrive sincroniza carpetas con ocho proveedores, monta archivos bajo demanda y conecta carpetas cifradas entre pares sin servidor de contenido TuxDrive. Cuentas a la izquierda, trabajos en el centro y actividad abajo.\n\nINICIO\n1. Conecte una cuenta. 2. Añada carpeta o unidad streaming. 3. Revise rutas, dirección y protección. 4. Mantenga una copia independiente antes de la primera sincronización bidireccional."),
    ("accounts", "2. Cuentas y autenticación", "Use + para Google Drive, OneDrive, Dropbox, Box, pCloud, MEGA, Proton Drive o Nextcloud. OAuth abre la web del proveedor; TuxDrive no recibe la contraseña. Proton puede pedir 2FA aparte. Los secretos están en rclone cifrado protegido por Secret Service. Repare desde menú de cuenta → Actualizar credenciales."),
    ("selective", "3. Selección de carpetas", "El árbol visual carga carpetas al expandir. Marque varias o toda la unidad. Google separa Mi unidad, Compartido conmigo y unidades compartidas. Editar cambia ubicación y ayuda a evitar solapamientos locales peligrosos."),
    ("sync", "4. Modos de sincronización", "Bidireccional propaga creación, cambios, movimientos y borrado. Solo recepción protege cloud; solo envío protege local. Callbacks procesan guardados locales y sondeo detecta remoto. Sincronizar inicia, Detener cancela y el interruptor pausa lo automático."),
    ("streaming", "5. Archivos bajo demanda", "Streaming monta la estructura con FUSE; el contenido baja al abrir. El punto debe estar vacío. En Nautilus mantenga un elemento sin conexión o devuélvalo a solo en línea. Desconecte antes de borrar el montaje."),
    ("actions", "6. Acciones del trabajo", "Abrir carpeta abre local; Abrir en línea va a la carpeta cloud; Compartir enlace copia un vínculo. Renombrar cambia solo la etiqueta. Editar cambia rutas/modo/filtros. Registro muestra detalles. Papelera elimina la definición, no los datos."),
    ("safety", "7. Historial, recuperación y protección", "Historial restaura versiones y reciclaje. Verificar compara; Conflictos exige decisión. Protección masiva/ransomware pausa ráfagas sospechosas. Detenga, revise registro, restaure versión sana, verifique ambos lados y reanude."),
    ("exceptions", "8. Excepciones y conflictos", "Las excepciones son reglas pulsables para temporales/bloqueos o rutas problemáticas verificadas; elimínelas para incluir de nuevo. Google marcado requiere aceptación explícita. Si duda, conserve ambas copias."),
    ("peer", "9. Carpetas privadas entre pares", "SFTP autenticado con clave de host fijada e identidad por dispositivo. El host elige carpeta/dirección/puerto/dispositivos; invitado importa invitación/QR y verifica huella. Roles lectura-escritura, solo lectura, envío o recepción. Revoque un dispositivo perdido."),
    ("privacy", "10. Tor y cierre seguro", "Servicio Onion v3 opcional, persistente y con autorización por dispositivo. Solo Tor, solo directo, sin relay, sin IP pública y nunca cloud detienen el tráfico, sin fallback silencioso. Distribuya la invitación en privado."),
    ("collaboration", "11. Documentos colaborativos", "Markdown/texto usa CRDT para editar offline y converger. Estado separado en .tuxdrive-collaboration; Exportar crea archivo normal. Presencia cifrada temporal, comentarios, sugerencias, aprobaciones y tareas. ODT/ODS experimental; DOCX/XLSX/PDF usa bloqueo/versiones/revisión."),
    ("profile", "12. Perfil cifrado y migración", "Perfil/migración cifra localmente con AES-256-GCM/scrypt y guarda en el proveedor OAuth elegido. Credenciales y claves privadas se excluyen por defecto. En el nuevo equipo conecte el mismo proveedor, inspeccione/restaure, reautorice y verifique rutas."),
    ("nautilus", "13. Integración con Nautilus", "Nautilus muestra emblemas sincronizado, activo, pendiente, pausa, error y streaming, además de acciones. Desactive en Configuración si hay conflicto y reinicie Nautilus."),
    ("updates", "14. Actualizaciones seguras", "Comprueba manifiesto firmado/caducable, Ed25519, URL, SHA-256, identidad/versión y tamaño antes de PolicyKit. Compruebe, lea notas, descargue/instale, autorice y reinicie. Un fallo deja intacta la instalación."),
    ("policies", "15. Red, batería, horario y ancho de banda", "Uso máximo no restringe. Puede pausar en red medida, batería baja o fuera de horario y limitar ancho de banda por trabajo. Los cambios aplazados no se pierden."),
    ("diagnostics", "16. Registros y diagnóstico", "Actividad en directo; registros de trabajos en ~/.cache/tuxdrive/logs y arranque/app/crash en ~/.local/state/tuxdrive. Para informar ejecute tuxdrive --diagnostics y --system-check --json, reproduzca una vez y oculte secretos. Nunca publique tokens, contraseñas, invitaciones ni claves privadas."),
    ("settings", "17. Configuración e idioma", "Configuración controla inicio, avisos, Nautilus, políticas, perfil y actualizaciones. La bandera superior cambia inmediatamente y guarda inglés, alemán, francés o español. Errores del proveedor/rclone pueden seguir en su idioma de origen."),
    ("uninstall", "18. Desinstalación segura", "Pause trabajos y desconecte montajes. apt remove tuxdrive quita el paquete, no los datos ni siempre la configuración. Exporte antes de borrar configuración, Secret Service o identidades; datos cifrados podrían quedar inaccesibles."),
))

_TOPICS = {"en": _EN, "de": _DE, "fr": _FR, "es": _ES}


def topics(language: str) -> tuple[HelpTopic, ...]:
    selected = _TOPICS.get(language, _EN)
    return tuple(HelpTopic(*item) for item in selected)
